### ISSUE TITLE
Numeric result is influenced on the order of quantities

### ISSUE THREAD

**Issue by dieter-wilhelm** [r-quantities/units#101]
Here's my test case:

```
library(units)# version 0.5-1, udunits2 0.13

## some definitions of quantities
Dens <- set_units(7800,kg/m^3)
D <- set_units(9,mm)
## Moment of Inertia for cylinder
R <- D /2 
L <- set_units(12,mm)
# Mass
pi*R^2*Dens*L
# Moment of intertia
MoI <- pi*R^4*L*Dens/2
## Moment of Inertia for hollow cylinder
## m(r1²+r2²)/2
R1 <- R;R1
R2 <- set_units(27 / 2,mm);R2
M <- Dens*pi*(R2^2 - R1^2)*L;M
####################################
## Here you'll see that the result is different for the following two lines
Dens*pi*(R2^2-R1^2)*L
pi*(R2^2-R1^2)*Dens*L
```

**Comment by Enchufa2** [comment]
Confirmed. Shorter example:

```r
a <- set_units(1, m^-3)
b <- set_units(1, mm)
a*b
#> 1e-06 1/m^2
b*a
#> 0.001 1/m^2
```

**Comment by Enchufa2** [comment]
Same problem in version 0.4-6 and in the `udunits` branch.

**Comment by edzer** [comment]
@mailund any idea?

**Comment by mailund** [comment]
I will have a look at it after I'm done teaching today.

**Comment by mailund** [comment]
@edzer can you assign the issue to me? I use assigned issues as my todo-list when I have time to program, so that will make sure I don't forget it. I cannot assign myself since I'm not set as a collaborator on the git repository.

**Comment by Enchufa2** [comment]
@mailund I've tried, but it seems that this is not possible unless 1) you are the author of the issue, or 2) @edzer sets you as a collaborator (and then you can do it yourself).

**Comment by mailund** [comment]
Ok, no worries then. I'm done with teaching and will start debugging as soon as I have had lunch. So I won't forget the issue after all :)

**Comment by Enchufa2** [comment]
Question: shouldn't `convert` return the new units? For example:

```r
units:::convert(set_units(1, m^3), "m^3", "l")
#> [1] 1000
#> attr(,"units")
#> $numerator
#> [1] "m" "m" "m"
#> 
#> $denominator
#> character(0)
#> 
#> attr(,"class")
#> [1] "symbolic_units"
```

**Comment by mailund** [comment]
That might be a solution as well, yes, but the problem was converting the operands before the operator in multiplication and division. I have fixed that and will make a PR now.

**Comment by Enchufa2** [comment]
Great, good one!

**Comment by mailund** [comment]
Actually, that units:::convert example confuses me. It shouldn't return a value with the type from the first argument. It should return `NA` since you cannot convert from cubic metres to litres. Instead, it looks like it thinks the result is 1000 cubic metres. Let me have a look at that.

You are right that the `from` field is redundant if the first argument already has a unit. When I wrote it (I think it was me), the first argument wasn't supposed to have a unit. The function was written to transform between two units and give us the transformation scalar.

**Comment by Enchufa2** [comment]
Why not? `1 L = 0.001 m^3`

**Comment by mailund** [comment]
You are right. I was being too fast for thinking there...

**Comment by mailund** [comment]
As far as I can see, we only use the `convert` function the way I remember, so I don't think there is much point in making it take a unit as its first argument. The `value` argument is only used for scaling when moving from one unit to another.
