### ISSUE TITLE
units lost after apply

### ISSUE THREAD

**Issue by CesarSancho** [r-quantities/units#103]
Not sure if this belongs here, I am playing with the units library and I am surprised to see that the units are lost after using apply, vapply, lapply... see the example below. Is this a desired behavior? could the library be improved to keep the units through these calls? is there any workaround?

thank you!

```
> (ddd = data.frame( c1=1:4*as_units("m"), c2=5:8*as_units("m") ))
   c1  c2
1 1 m 5 m
2 2 m 6 m
3 3 m 7 m
4 4 m 8 m
> sum(ddd$c1) # units kept ok
10 m
> sum(ddd$c2) # units kept ok
26 m
> apply(ddd,1,sum)  # units lost!!
[1]  6  8 10 12
```

**Comment by Enchufa2** [comment]
R base is a minefield for custom classes in data frames such as units, because many functions simplify and drop attributes and classes. The `apply` family is one of this kind. I don't know any workaround for `apply`, because it internally uses `as.matrix.data.frame` and `vapply`, but there are workarounds for others:

```r
# drops units
sapply(ddd, sum)
# OK, but the output is a list
sapply(ddd, sum, simplify=FALSE)
# dropped again
unlist(sapply(ddd, sum, simplify=FALSE))
# but this works
do.call(c, sapply(ddd, sum, simplify=FALSE))
# which is the same as
do.call(c, lapply(ddd, sum))
```

**Comment by edzer** [comment]
We could check how things work out with `purrr`?

**Comment by Enchufa2** [comment]
`purrr::map` always returns a list, so it's equivalent to `lapply`.

**Comment by t-kalinowski** [comment]
`purr::modify()` preserves classes (it's built on `[<-`) and I think default methods for atomic vectors will be provided in the next [release](https://github.com/tidyverse/purrr/pull/410)

**Comment by CesarSancho** [comment]
I gave it a try and dplyr and purrr work form me; I am pasting some basic samples below. Thank you  very much!

```
> purrr::map( ddd, function(x){paste(format(x),collapse="+")})
$c1
[1] "1 m+2 m+3 m+4 m"

$c2
[1] "5 m+6 m+7 m+8 m"

> purrr::modify( ddd, function(x){x*3} )
    c1   c2
1  3 m 15 m
2  6 m 18 m
3  9 m 21 m
4 12 m 24 m

> ddd %>% group_by(c1 %% 2) %>% summarize(sum(c2))
# A tibble: 2 x 2
  `c1%%2` `sum(c2)`
    <[m]>     <[m]>
1     0 m      14 m
2     1 m      12 m

```
