### ISSUE TITLE
matmult operator

### ISSUE THREAD

**Issue by Enchufa2** [r-quantities/units#126]
This is a summary of the issue, as discussed by email, to take a decision about it eventually.

> Both errors and units defined the matmult operator as an S3 generic. The new package quantities lists both packages in Depends, because all their functions need to be in the search path (a user may want to change the units of a quantity, the errors, install new units, etc.). This double export generated a warning that won't pass CRAN checks, because both Depends are defining the same generic.
> 
> There are several options here:
> 
> 1) quantities uses Imports instead of Depends, and reexports *all* functions from both packages (except for the matmult operator from *one* package). I think this is a very verbose solution and hard to maintain.
> 
> 2) We stop supporting this operator.
> 
> 3) errors stops supporting this operator (currently, it just shows a warning saying that errors are dropped).
> 
> 4) units and errors export this operator dynamically. This is tricky, but it can be done. Two things are needed: a conditional assignment in .onLoad, and an exportPattern in the NAMESPACE to catch that assignment. The problem is that the exportPattern is removed by roxygen2 each time you roxygenise the package (AFAIK, there's no way of telling roxygen2 "please, don't touch this line from the NAMESPACE").

(1) and (4) don't scale, and the drawbacks are much more important than the gain. We are in (3) right know, because I already dropped support in the master version of errors (it was just showed a warning), and quantities works fine. Yet it is to decide whether we should go for (2) and drop support in units too or not.

**Comment by edzer** [comment]
I vote for 2.

**Comment by Enchufa2** [comment]
Then, I can arrange a PR (I developed some practice already ;-) ). What about commenting out that piece of code to remember it in the future (just in case we ever hit our heads and decide to switch to S4)? Or do you prefer to remove it entirely?

**Comment by edzer** [comment]
Yes, uncomment is a good idea.
