### ISSUE TITLE
Multiplier not applied in units<-

### ISSUE THREAD

**Issue by AlexCast** [r-quantities/units#131]
When doing:
var <- 1:10
units(var) <- with(ud_units, µL/L)

"var" would get the correct unit (unitless, 1), only if the multiplier (10^-6) was applied; this is not the case now so the values are not correct. I know that there is a way around, by:
var <- 1:10 * with(ud_units, µL/L)

but shouldn't this work with units<-?

Also, as the multiplier 10^6 might be convenient when working with small values (to avoid scientific notation on the axis of plots for example), couldn't the unitless reflect the ratio? That is, instead of 1, be 10^-6?

**Comment by AlexCast** [comment]
Adding to the issue, this also don't work:

var <- set_units(1:10, µL/L)
Error: In ‘µL/L’ the numeric multiplier ‘1e-06’ is invalid. 
Use `install_conversion_constant()` to define a new unit that is a multiple of another unit.

**Comment by edzer** [comment]
This now works in the udunits branch (soon master):
```r
> var <- set_units(1:10, µL/L)
> var
Units: µL/L
 [1]  1  2  3  4  5  6  7  8  9 10
```
