### ISSUE TITLE
make label: unitless

### ISSUE THREAD

**Issue by AlexCast** [r-quantities/units#133]
Hi guys,

Is possible to add a way for make_unit_label to represent a unitless variable with 1 or 'unitless'? Now it result in empty brackets.

Kind regards,

**Comment by edzer** [comment]
Which version of `units` are you using? I see:
```r
u = set_units(3)
plot(u)
```
![x](https://user-images.githubusercontent.com/520851/40071667-bd3131ae-5871-11e8-99d4-76b4f9f3c558.png)

**Comment by AlexCast** [comment]
Hi @edzer , 

I'm using version 0.5.1. Your example works fine for me as well. So it seems to happen when we change some options in units. Here is my example:

```{r}
library(units)
units_options(negative_power = TRUE, parse = TRUE, group = c("(", ")"))
u = set_units(3)
plot(u)
```

**Comment by edzer** [comment]
It goes away if you don't set `negative_power` to `TRUE`, but I guess that still leaves it an issue.

**Comment by edzer** [comment]
See #150
