### ISSUE TITLE
cran demands fixing memory leaks

### ISSUE THREAD

**Issue by edzer** [r-quantities/units#135]
I got an email from CRAN yesterday, stating
```
This concerns packages

GMSE RxODE skpr biclust fst pvrank sf

Please see the CRAN check results page for your package, especially the 'Addiitional issues'.

Please correct ASAP and before June 9 to safely retain the package on CRAN.
```
The errors are found [here](https://www.stats.ox.ac.uk/pub/bdr/memtests/valgrind/sf/). Most of the memory leaks are from `udunits2`; I guess this calls for a rather quick update of units, based on the `udunits` branch (where none of the XPtr stuff should end up in the API).

**Comment by Enchufa2** [comment]
There are lots of "possibly lost" records, but those seem to be internal to `libudunits2`, and therefore I'd say that updating `units` wouldn't change anything. I hope the trigger for this request is based solely on the 12 "definitely lost" records, which come from `udunits2` and are fixable by updating `units`. Otherwise... this is a big problem. I also wonder why there is no valgrind note in the `units` checks page.

**Comment by edzer** [comment]
Oh, `units` might get its turn in another email. ;-)

**Comment by Enchufa2** [comment]
But I mean, apparently [there are no valgrind issues here](https://cran.r-project.org/web/checks/check_results_units.html)... How is this possible?

**Comment by edzer** [comment]
Valgrind checks take ages; CRAN volunteers may have had their hands full with 3.5.0, or other issues.

**Comment by edzer** [comment]
Ah, no, the better explanation is of course that packages without compiled code cannot themselves be the cause for memory errors (other than caused by R).

**Comment by Enchufa2** [comment]
Let me know if there is something I can do. To start with, the `udunits` branch will probably break `constants`, although there are several changes in `master` that still need to be merged.

**Comment by edzer** [comment]
branch udunits is again in sync with master; could you pls check `constants`?

**Comment by Enchufa2** [comment]
Broken, but easy to solve. [This line fails](https://github.com/r-quantities/constants/blob/master/R/constants.R#L105). Previous versions of `install_conversion_constant` proceeded to install new symbols. Now, it requires a call to `install_symbolic_unit` before. Is this correct? Or do you prefer to keep the previous behaviour?

**Comment by t-kalinowski** [comment]
Before pushing the udunits branch to cran, can we please fix the bug described in #91. 
With the current udunits branch
```
library(units)

# user has two vectors, wants to normalize both to the one unit, then drop units
x <- set_units(1, ug/kg)
y <- set_units(1, mg/kg)
combined <- set_units(c(x, y), mg/kg)
drop_units(combined) 
#> [1] 1e-15 1e-12
# should be 0.001, 1
```

**Comment by edzer** [comment]
Thanks; I'll try to to dig into this over the weekend, and come with a proposal.

**Comment by Enchufa2** [comment]
@edzer See [my question above](https://github.com/r-quantities/units/issues/135#issuecomment-392587596), please.
