### ISSUE TITLE
remove_symbolic_unit Succeeds when the Unit Doesn't Exist

### ISSUE THREAD

**Issue by billdenney** [r-quantities/units#139]
`remove_symbolic_unit` should provide a warning to the user if the unit doesn't exist.  I don't know the best way to test for a unit existing in the system, but the change should be added here: https://github.com/r-quantities/units/blob/8f811660338a08cd4f35ea1b76d762c2142d7670/R/user_conversion.R#L30

I'd expect a warning in the following code:

``` r
library(units)             
#> udunits system database from C:/Users/Bill Denney/Documents/R/win-library/3.4/units/share/udunits
remove_symbolic_unit("foo")
```

**Comment by edzer** [comment]
Thanks, should work now!

**Comment by billdenney** [comment]
Thanks!
