### ISSUE TITLE
Enable installation of base units

### ISSUE THREAD

**Issue by Enchufa2** [r-quantities/units#144]
Raised by @billdenney in #134. Currently, `install_symbolic_unit` install a dimensionless unit. Now that we have complete access to the udunits API since v0.6-0, we can easily enable also the installation of base units. There would be two ways to go:

1. Add a new parameter (`type`?, by default `type="dimensionless"` for compatibility reasons) to `install_symbolic_unit`.
2. Deprecate the latter and define separate installers: `install_base_unit` and `install_dimensionless_unit`.

**Comment by billdenney** [comment]
Thanks for opening this.  My preference is 1 because I think of it as a very similar operation to add a unit, and I’m more likely to remember an argument than a function. :)

Either works reasonably, though.

**Comment by edzer** [comment]
since there are two options, "dimensionless" and "base", I made dimensionless a boolean:
```r
> library(units)
udunits system database from /usr/share/xml/udunits
> install_symbolic_unit("person", dimensionless=FALSE)
> set_units(1, person)
1 person
> set_units(1, person) + set_units(1, kperson)
1001 person
> set_units(1, person) + set_units(1, rad)
Error: cannot convert rad into person
```

**Comment by billdenney** [comment]
That looks great!
