### ISSUE TITLE
valid_udunits Only Reports Units in the Default Loaded XML

### ISSUE THREAD

**Issue by billdenney** [r-quantities/units#146]
When generating new units with `install_unit_conversion` or `install_symbolic_units`, they will not show up in `valid_udunits`.  For example, I would have expected the following to show "foo" in the valid_udunits output (i.e. I expected the result at the end to be `TRUE`).

``` r
library(units)                          
#> udunits system database from C:/Users/Bill Denney/Documents/R/win-library/3.4/units/share/udunits
install_symbolic_unit("foo")            
"foo" %in% valid_udunits()$name_singular
#> Loading required namespace: xml2
#> udunits system database read from C:/Users/Bill Denney/Documents/R/win-library/3.4/units/share/udunits
#> [1] FALSE
```

**Comment by edzer** [comment]
Isn't the documentation of `valid_udunits` pretty clear that your expectation is false?

**Comment by billdenney** [comment]
You're right.  I assumed what it did without looking at the docs.
