### ISSUE TITLE
How to print unitless

### ISSUE THREAD

**Issue by edzer** [r-quantities/units#150]
We now have
```r
> set_units(33, 1)
33 1
```
but [bipm](https://www.bipm.org/en/publications/si-brochure/section5-3-7.html) rightly says not to do this. Still, it is useful to not only print
```r
33
```
in order to make clear it has units; otoh, that differs from printing of `33`:
```r
> 33
[1] 33
```
Options I can think of, better than `1`:

1 `33 []`
2 `33 [-]`
3 `33 -`

Note that this propagate into plots. Opinions?

**Comment by Enchufa2** [comment]
I think it should be something parseable. The minus sign is problematic in that sense. Also, the square brackets should be configurable for all units (e.g., whether to display `m` or `[m]` or `(m)`...). Also note that this affects to the formatting of a single number, which in turn affects how they are presented in data frames. For general vectors and arrays, "Units: unitless" or "Units: dimensionless" can be displayed.

**Comment by edzer** [comment]
Why should it be parseable?

**Comment by Enchufa2** [comment]
Given that we provide parsers to recognise and import units and errors in standard representations, I think it's not reasonable to print out ad hoc characters in corner cases. Moreover, a minus sign may be misleading and potentially cause further issues.

Personally, if I had some dimensionless unit, I would care to define one with a proper name to be displayed correctly. And if I wanted it nameless, I would expect an empty symbol, not a minus sign or other random character (I wouldn't expect a `1` either).

If I recall correctly, there's another open issue to use the grouping characters not only in plots, but in general. If unit `1` is displayed as an empty symbol, the defult behaviour will be then `33 []`, which is fine IMHO.

**Comment by edzer** [comment]
I made this into an option; we now have:
```r
library(units)
# udunits system database from /usr/share/xml/udunits
library(magrittr)
u = set_units(1:3)
u
# Units: [1]
# [1] 1 2 3
u[1]
# 1 1
data.frame(u)
#     u
# 1 1 1
# 2 2 1
# 3 3 1
tibble::tibble(u)
# # A tibble: 3 x 1
#       u
#     [1]
# 1     1
# 2     2
# 3     3

units_options(unitless_symbol = "")
u = set_units(1:3)
u
# Units: []
# [1] 1 2 3
u[1]
# 1 []
data.frame(u)
#      u
# 1 1 []
# 2 2 []
# 3 3 []
tibble::tibble(u)
# # A tibble: 3 x 1
#       u
#      []
# 1     1
# 2     2
# 3     3
```

**Comment by Enchufa2** [comment]
Yeap, leaving it as an option can be a good one. I'm still not convinced though about why should I get brackets in the data frame if I defined `unitless_symbol=""`, not `unitless_symbol="[]"`.

Let me keep playing the devil's advocate. :) What Python's `units` package does is to automatically downgrade nameless dimensionless units to just numeric.

**Comment by edzer** [comment]
You can do
```r
library(units)
# udunits system database from /usr/share/xml/udunits
units_options(unitless_symbol = "", group = c("", ""))
data.frame(u = set_units(1:3))
#    u
# 1 1 
# 2 2 
# 3 3 
```
but I think this doesn't help users as they may think that `u` _is_ just numeric (in case they don't notice the misalignment). Note that this is just about _printing_, not about what _is in the data.frame_.

Thanks for checking what Python does, I think that is important. We silently upgrade numeric to unitless in
```r
> units_options(unitless_symbol = "")
> set_units(1) * 2
2 []
```
but I'd like to add an option that raises a warning here. I consider numeric to have _missing_ units, rather than being _unitless_. R's main strength over Python is dealing properly with what is missing.

**Comment by Enchufa2** [comment]
> R's main strength over Python is dealing properly with what is missing.

Agree. The thing is that as soon as you pass units to other functions (e.g., `ggplot2`), numeric operations will happen; numeric operations that are valid and should work (e.g., scaling axes, checking some limits). And that's why I implemented `warn_once` for errors.

**Comment by edzer** [comment]
I agree, and that is why I wanted to make even more rigorous units handling optional: it comes at the cost of being able to use them in other packages.
