### ISSUE TITLE
drop_units() stopped working for values which are not of class "units"

### ISSUE THREAD

**Issue by phirsch** [r-quantities/units#159]
drop_units() stopped working for values which are not of class "units" as of version 0.6-0 from CRAN.

Up to version 0.5-1, drop_units() used to work with values of any type (returning the value x unchanged if class(x) did not contain "units"). In version 0.6-0, drop_units() has been converted into an S3 method without a default implementation (#118). For non-"units" arguments it therefore results in an error message, e.g.:

``` r
units::drop_units(1)
#> Error in UseMethod("drop_units"): no applicable method for 'drop_units' applied to an object of class "c('double', 'numeric')"
```

Created on 2018-07-04 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

The previous behaviour could be restored by providing a drop_units.default() implementation, e.g.:

``` r
drop_units.default <- identity
```

**Comment by Enchufa2** [comment]
Yes, this was intentional, because `drop_units` has no meaning for objects without units.

**Comment by edzer** [comment]
As an alternative, you could use `as.numeric`, which drops units for `units` and does nothing for numeric data. I agree with @Enchufa2 - if `drop_units` cannot drop any units, it should give an error.

**Comment by phirsch** [comment]
I see. I got my interpretation from the documentation which suggested to me that something like `mutate_all(drop_units)` in a `dplyr` pipe would be fine (e.g. for plotting):
> [Value:] the numeric without any units attributes, while preserving other attributes like dimensions or other classes.

**Comment by phirsch** [comment]
Anyway, I am happy to change my workflow if this is the intended behaviour. I just could not think of any downside of simply passing through non-`units` objects unchanged given the intention of `drop_units`.

It might be helpful to have a dedicated predicate `is_units` to test whether an object is a `units` instance, e.g. to be used with `dplyr::mutate_if`. Thoughts?

**Comment by Enchufa2** [comment]
`if (inherits(x, "units")) drop_units(x)` should work. Or simply `set_units(x, NULL)`.

**Comment by phirsch** [comment]
Yes `inherits(x, "units")` would work. It does, however, require knowledge of an implementation detail.

I just think that the previous behaviour (drop any unit if there is one, otherwise do nothing) was quite handy, but there might be downsides which I do not realize yet. I am totally happy if you just close the issue as WONTFIX.

**Comment by MatthieuStigler** [comment]
Hi

I agree that `drop_units()` working also on non-unit data can be convenient. `as.numeric()` is a little tricky, as `is.numeric()` would return TRUE anyway, with or without units. So indeed, a `has_units` or `drop_if_units()`  could seem convenient from a user perspective!?

**Comment by Enchufa2** [comment]
As I said in a previous comment, `set_units(x, NULL)` does exactly that.
Therefore, I don't see how a duplicated feature could be useful. In fact,
the other way around: I think that is useful to have also something that
fails if there are no units.

What we can do is to add this to the documentation of `drop_units`, if it's
not there.
