### ISSUE TITLE
data frame column with unit=1 looks odd.

### ISSUE THREAD

**Issue by barryrowlingson** [r-quantities/units#170]
If I divide one unitted vector by another I get a vector with units of "1":
```
x=1:4;y=x^2;units(x)="m/s";units(y)="m/s"
z = x/y
z
#  Units: 1
#  [1] 1.0000000 0.5000000 0.3333333 0.2500000
```

I'm sure there's an argument for not dropping the "units" at this point, but that's not my problem here. If I make a data frame with this vector it displays with the "1" looking very much like a column of the data:

```
data.frame(r = z)
#             r
# 1 1.0000000 1
# 2 0.5000000 1
# 3 0.3333333 1
# 4 0.2500000 1
```

with no clue that this is a unit, except the mysterious blank space above the actual data numbers.  In a complex data frame this could easily be mistaken.

This could be fixed by either dropping units magically if they are dimensionless, or changing the `format` method to not print "1" in this case.

I could use `drop_units` when I do this kind of division, but that fails if the argument isn't a vector of unitted values, and I don't know what my function might get called with.

```
Package: units
Version: 0.6-0
```

**Comment by Enchufa2** [comment]
In the current master branch, grouping characters (square brackets, by default; see `?units_options`) are displayed by default:

```r
x=1:4;y=x^2;units(x)="m/s";units(y)="m/s"
z = x/y
z
#> Units: [1]
#> [1] 1.0000000 0.5000000 0.3333333 0.2500000
data.frame(r = z)
#>               r
#> 1 1.0000000 [1]
#> 2 0.5000000 [1]
#> 3 0.3333333 [1]
#> 4 0.2500000 [1]
```

**Comment by Enchufa2** [comment]
Personally, I prefer to drop units in these cases, but also appreciate the advantages of having an homogeneous behaviour by preserving the class. There is an option called `unitless_symbol` (not on CRAN yet I think) which by default is `"1"`; you can set it to `""` (see `?units_options`).

**Comment by edzer** [comment]
There's a semantic difference between a `numeric` vector in R, and a `units` vector having `1` as unit (unitless). The first one can have any unit, the second one not.
