### ISSUE TITLE
Allow installation of units which end (and perhaps begin) with a digit 

### ISSUE THREAD

**Issue by stephenbi** [r-quantities/units#171]
Hello,
I'm working with climate and economics data, and I would like to define base units such as "tCO2" (tonne of carbon dioxide) and "US$05" (dollars at 2005 value).

This is currently impossible because any digits at the end of a unit string are interpreted as an exponent:

`install_symbolic_unit("tCO2")`
`x <- set_units(100, "tCO2")`

`Error: In ‘tCO^(2)’, ‘tCO’ is not recognized by udunits. `

May I suggest adding an option in units_options.R which toggles how exponents are parsed? E.g. one setting would require the use of a carat ^ before the exponent.

Also...

Trying to work around this, I noticed that I can't define units beginning with digits either. 

`install_symbolic_unit("05_USD")`
`y <- as_units("05_USD")`

`Error: In ‘05_USD’, ‘05_USD’ is not recognized by udunits.`

Practically speaking, I believe I only need one solution or the other, and I prefer the first, but I'd be interested to know what's going on in the second issue as well.

Thanks in advance!

**Comment by Enchufa2** [comment]
This is a limitation imposed by the underlying `udunits2` library. It parses leading numbers as multiplicative constants and trailing ones as exponents, so I don't think there's anything that `units` can do at this respect.

**Comment by edzer** [comment]
I also don't see this happening, because of the change it would require in the underlying C library (which is legacy). You can do this, for instance:
```r
> x <- set_units(100, "tCO2_")
> x
100 [tCO2_]
```
