### ISSUE TITLE
RNetCDF sets UDUNITS2_XML_PATH

### ISSUE THREAD

**Issue by edzer** [r-quantities/units#175]
Don't know if this could lead to problems, but good to know that
```r
Sys.getenv("UDUNITS2_XML_PATH")
# [1] ""
library(RNetCDF)
Sys.getenv("UDUNITS2_XML_PATH")
# [1] "/home/edzer/R/x86_64-pc-linux-gnu-library/3.5/RNetCDF/udunits/udunits2.xml"
library(units)
# udunits system database from /home/edzer/R/x86_64-pc-linux-gnu-library/3.5/RNetCDF/udunits
# Warning message:
# In .get_ud_xml_dir(TRUE) :
#   multiple udunits databases present: /home/edzer/R/x86_64-pc-linux-gnu-library/3.5/RNetCDF/udunits/udunits2.xml /usr/share/xml/udunits/udunits2.xml
```
So this triggers a warning if `units` is loaded after `RNetCDF`.

**Comment by Enchufa2** [comment]
But it works ok, right? And even if it leads to problems, the user is properly informed thanks to the warning. Should we do something else? Or can we close this?

**Comment by edzer** [comment]
Let's leave it open until we've taken action. I think that using two packages correctly should not lead to an error. The question is should we propose the RNetCDF folks to move, or should we move? We could for instance decide to lower the warning to a message.

**Comment by Enchufa2** [comment]
RNetCDF no longer sets this.
