### ISSUE TITLE
set_units on an integer units object converts storage type to double

### ISSUE THREAD

**Issue by kendonB** [r-quantities/units#181]
``` r
library(tidyverse); library(units)
#> udunits system database from C:/R/Library/3.5/units/share/udunits
var <- c(1L) %>% set_units("m") 
typeof(var)
#> [1] "integer"
var %>% 
  set_units("m") %>% 
  typeof()
#> [1] "double"
```

<sup>Created on 2018-12-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by Enchufa2** [comment]
Thanks for the report! Fixed in #182, ready to merge.

**Comment by edzer** [comment]
Ah, this gives `"integer"` in the second case as well. I had in mind to have both return `"double"`. Did we somewhere document that units should have, get, or keep, a specific type?

**Comment by Enchufa2** [comment]
AFAIK, the documentation doesn't specify anything about this. My understanding is that @kendonB expects `units` to honor what base R does (please, correct me if I'm wrong); i.e., to keep the provided type until it's not possible anymore, and I thought it was reasonable. For example, `seq` returns integers if possible, and so does `seq.units`. Most units are continuous, but some may not (I can think of counts right now), so it would be nice to support integers.

**Comment by edzer** [comment]
Makes sense!

**Comment by kendonB** [comment]
"My understanding is that @kendonB expects units to honor what base R does (please, correct me if I'm wrong); i.e., to keep the provided type until it's not possible anymore" - this is the correct understanding.

**Comment by Enchufa2** [comment]
@edzer Are we aligned then? Should we merge #182?

**Comment by edzer** [comment]
All set - thanks!
