### ISSUE TITLE
attempt coercion using as_units for binary operators?

### ISSUE THREAD

**Issue by kendonB** [r-quantities/units#189]
It would be nice to be able to use string representations of quantities in binary operations involving `units` objects. For example:
``` r
library(units)
#> udunits system database from C:/R/Library/3.5/units/share/udunits
one_metre <- as_units(1, "m")  
one_metre > "2 m"
#> Error in Ops.units(one_metre, "2 m"): both operands of the expression should be "units" objects
one_metre > as_units("2 m")
#> [1] FALSE
```

<sup>Created on 2019-01-31 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

I think that allowing users to use the string representation of a quantity in these situations is pretty benign but results in much nicer looking code that have `as_units` everywhere. Can anyone think of a situation where such a reduction in safety might cause problems?

**Comment by edzer** [comment]
If both operands of `>` are of different type, R doesn't know which method for `>` to choose, and I don't think you can tell it that it should _always_ convert "2 m" to units rather than `2 [m]` to character, regardless which comes first.
```r
" 3 m" > "2 m"
# [1] FALSE
```

**Comment by kendonB** [comment]
Ah I see. Is there a case for attempting coercion of the second argument?

**Comment by edzer** [comment]
I don't like the idea that `a > b` would give something else as `b < a`.

**Comment by Enchufa2** [comment]
> I don't like the idea that `a > b` would give something else as `b < a`.

Well, apparently, the Ops group is special: it implements double dispatch to preserve the commutative property of many operators. So in principle, this concern shouldn't be a problem.

**Comment by edzer** [comment]
You're right. But suppose we'd go this path, users would have to know this, in order not to end up doing things like
```r
> "10 m" < "2 m"
[1] TRUE
```
because `units` makes them believe expressions like `"2 m"` work as units expressions.

**Comment by Enchufa2** [comment]
Agree. That shifts the balance.
