### ISSUE TITLE
RStudio and Travis CI build check do NOT match (libudunits2.so)

### ISSUE THREAD

**Issue by laresbernardo** [r-quantities/units#190]
I have opened a ticket in StackOverFlow as well: https://stackoverflow.com/questions/54678006/rstudio-and-travis-ci-build-check-do-not-match-libudunits2-so
Don't know who's issue is it but I'm sure you guys can help me with it!
Thanks

**Comment by Enchufa2** [comment]
Travis can't automagically detect that you need libudunits2. You must to specify that this library needs to be installed by adding the following to your `.travis.yml`:

```
addons:
  apt:
    packages:
      - libudunits2-dev
```

And, please, don't crosspost.
