### ISSUE TITLE
leap year in year 200 not handled the same as in R

### ISSUE THREAD

**Issue by kendonB** [r-quantities/units#194]
``` r
library(units)
#> udunits system database from C:/R/Library/3.5/RNetCDF/udunits
x1 <- as_units(1, "seconds since 200-02-28 00:00:00 +00:00")
units(x1) = units:::symbolic_unit("seconds since 1970-01-01 00:00:00 +00:00")
as.POSIXct.numeric(as.numeric(x1), tz = "UTC", origin = as.POSIXct("1970-01-01 00:00:00", 
                                                                   tz = "UTC"))
#> [1] "0200-02-27 00:00:01 UTC"

x2 <- as_units(1, "seconds since 200-03-01 00:00:00 +00:00")
units(x2) = units:::symbolic_unit("seconds since 1970-01-01 00:00:00 +00:00")
as.POSIXct.numeric(as.numeric(x2), tz = "UTC", origin = as.POSIXct("1970-01-01 00:00:00", 
                                                                   tz = "UTC"))
#> [1] "0200-03-01 00:00:01 UTC"

# units thinks there's a leap day there
(as.numeric(x1) - as.numeric(x2))/86400
#> [1] -2

# R does not think there's a leap day there
as.Date("0200-02-29")
#> Error in charToDate(x): character string is not in a standard unambiguous format
```

<sup>Created on 2019-03-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

I came across this problem in real life when using `stars::read_ncdf` on this file which stores dates with "0000-01-01" as the origin: 

[mrso_Lmon_FGOALS-g2_historical_r2i1p1_200001-200912.zip](https://github.com/r-quantities/units/files/2921074/mrso_Lmon_FGOALS-g2_historical_r2i1p1_200001-200912.zip)

The above code is inside `as.POSIXct.units`.

https://calendarhome.com/calculate/days-between-2-dates agrees with R and not `units`.
![image](https://user-images.githubusercontent.com/5327505/53668106-cd35c880-3cd7-11e9-8cd7-685bbef279c1.png)

**Comment by edzer** [comment]
[udunits documentation about this](https://www.unidata.ucar.edu/software/udunits/udunits-current/doc/udunits/udunits2lib.html#Time): "You should use a true calendar package rather than the UDUNITS-2 package to handle time".

**Comment by kendonB** [comment]
Should I open an issue in stars then?

**Comment by edzer** [comment]
If you have a clear idea what stars should do differently, yes.

**Comment by Enchufa2** [comment]
Please, report this [upstream](https://github.com/Unidata/UDUNITS-2/issues).

**Comment by kendonB** [comment]
See here: https://www.unidata.ucar.edu/software/thredds/current/netcdf-java/CDM/CalendarDateTime.html

It looks like there's a separate package for handling dates from alternative calendars.

The above problem arises because udunits by default uses the "mixed Gregorian/Julian calendar" whereas R uses ISO8601. I wonder if it's easy to just switch over what udunits uses in the background?

**Comment by Enchufa2** [comment]
It's not possible. It seems that it only supports the Julian-Gregorian calendar, which means that you cannot parse Gregorian dates before 1582 with `udunits` or `units` (i.e., they should be converted to Julian dates before feeding them to `units`).
