### ISSUE TITLE
Units conversion is burried in the docs

### ISSUE THREAD

**Issue by Demetrio92** [r-quantities/units#200]
1. `set_units` describes as 
> A pipe friendly version of units<-

which is not helpful at all as `?'units<-'` opens docs for `base::difftime`
It says "see also as_units" which then provides a full, but way to lengthy docs to both functions

2. ReadMe to this repo only shows automatic conversion

3. Vignette explains only the pipe-unfriendly version:
```R
b = a
units(b) <- with(ud_units, km/h)
b
```

4. `as_units` does not behave as expected. E.g. it's inconsistent with the rest of R-syntax
Consider
```R
x = 2.5
x %>% as.character()  #  converts number x to a character
```
Against
```R
x = 2.5 %>% set_units('mile')
x %>% as_units('km')  # does not work
x %>% as.units('km')   # does not work and is deprecated
x %>% set_units('km')  #  converts number in miles x to a number in kilometres
```

**Comment by Demetrio92** [comment]
If the maintainers agree, I am willing to submit a PR fixing at least the first 3.

**Comment by Enchufa2** [comment]
I'll be glad to review a PR.
