### ISSUE TITLE
strict latin1 environment

### ISSUE THREAD

**Issue by edzer** [r-quantities/units#202]
This message came from Brian Ripley (CRAN):

This concerns packages

CHNOSZ SARP.moodle caret dplyr fpeek fs gestalt hyphenatr incadata jpndistrict lobstr lucr pillar postGIStools rbison rchie rcmdcheck rcrossref rdatacite rerddap rgbif rplos skimr snakecase styler svglite swirl swirlify taxize testthat textTinyR traitdataform units urltools

which are failing their checks in a strict Latin-1 locale: see the debian-clang results.  (Several of these seem to stem from vcr.)

On Linux, such a locale can be ensured via LC_CTYPE=en_US (which may need installing for distros that micro-package).  AFAWK it cannot be done on Windows.

1) The character in don't is an (ASCII) apostrophe, not a right quote:

don’t

(with a right quote) is used in packages CHNOSZ dplyr ptstem skimr styler text2vec textTinyR (and others not failing).

2) en and em dashes are not portable, found in packages
CHNOSZ SARP.moodle caret dplyr gestalt ptstem quanteda rchie rcrossref rdatacite rerddap rgbif rplos taxize textTinyR traitdataform units .

3) Using \uxxxx coding for non-ASCII chars in R character strings should help in some cases (see 'Writing R Extensions').

Please correct before May 10 to safely retain the package on CRAN.

**Comment by Enchufa2** [comment]
Strict latin1. Really? Ok, I'll have a look later. It seems to be the Celsius test. There's also a valgrind error, but that should be gone in the current development version.

**Comment by Enchufa2** [comment]
The ERROR is reproducible for the CRAN version as follows:

```
LC_CTYPE=en_US R CMD check --as-cran units_0.6-2.tar.gz
```

The current development version passes the check cleanly, so you can just submit an update.

**Comment by Enchufa2** [comment]
Kind reminder. ;-)

**Comment by edzer** [comment]
On CRAN now!

**Comment by Enchufa2** [comment]
We failed to notice [this line](https://github.com/r-quantities/units/blob/master/tests/testthat/test_misc.R#L90)... and thus it still fails on Debian. :(

**Comment by Enchufa2** [comment]
Sorry for missing that; you'll probably hear from CRAN soon... Now it should work both on Debian with strict latin1 and on Windows.

**Comment by Enchufa2** [comment]
I can't believe it... [this](https://github.com/r-quantities/units/blob/master/tests/testthat/test_misc.R#L88) is still ERRORing!? I was sure that the checks were successful. Maybe I used the wrong terminal? At least the test passes with ISO8859-1 for sure.

The only solution then is to skip the test...
