### ISSUE TITLE
Allow missing unit?

### ISSUE THREAD

**Issue by paulponcet** [r-quantities/units#203]
`NA_unit_` could be created as follows: 

    NA_unit_ = structure(list(numerator = NA_character_, denominator = character(0)), 
                         class = "symbolic_units")

Operations `+`, `-`, etc. on vectors could then be updated in order to propagate a missing unit. For instance if a vector `x` is in meters and `y` has a missing unit, then `x * y` should have a missing unit.

**Comment by Enchufa2** [comment]
This is being tracked in #163. Please, continue the discussion there.
