### ISSUE TITLE
"US_liquid_gallon" to "gal" conversion fails

### ISSUE THREAD

**Issue by iembry** [r-quantities/units#204]
Hi, I am using units 0.6-3 and I attempted to use the following R code to specify gal as equivalent to US_liquid_gallon:

    > # create unit of gallon from US liquid gallon unit
    > install_conversion_offset("US_liquid_gallon", "gal", 1)
    Error in install_conversion_offset("US_liquid_gallon", "gal", 1) :
    exactly one of (from, to) must be a known unit

US_liquid_gallon is a singular name in the XML database with no symbol so why doesn't the conversion above work?

Thank you.

**Comment by Enchufa2** [comment]
The error message is pretty clear: "exactly one of (from, to) must be a known unit". If you checked that `US_liquid_gallon` is a valid unit, this means that `gal` is also a valid unit, and you cannot set a conversion between two existing units. One of them must be a new unit. The reason for this is simple: two existing units already have a meaning, so you can corrupt the units system badly if you set a new conversion.

In fact, according to the XML database,

```xml
<unit>
  <comment>Unit is temporarily accepted for use with the SI.</comment>
  <def>cm/s^2</def>
    <aliases>
      <name><singular>gal</singular></name>
    </aliases>
  <definition>unit of acceleration equal to 1 cm per second squared</definition>
</unit>
```

**Comment by iembry** [comment]
Hi @Enchufa2, please see the following:

> "gallon" %in% valid_udunits()$symbol
udunits system database read from /usr/share/xml/udunits
[1] FALSE

> "gal" %in% valid_udunits()$name_singular
udunits system database read from /usr/share/xml/udunits
[1] TRUE

> "gallon" %in% valid_udunits()$name_singular
udunits system database read from /usr/share/xml/udunits
[1] FALSE

> "US_liquid_gallon" %in% valid_udunits()$name_singular
udunits system database read from /usr/share/xml/udunits
[1] TRUE

> install_conversion_offset("US_liquid_gallon", "gallon", 1)
Error in install_conversion_offset("US_liquid_gallon", "gallon", 1) : 
  exactly one of (from, to) must be a known unit
  
  
According to the database, "US_liquid_gallon" exists, but "gallon" does not exist. Why does the last line of code with the conversion not work in this instance?

I have tried the last line previously and it worked, but this time it is not working.

Thank you.

Irucka

**Comment by Enchufa2** [comment]
According to the database, "gallon" exists, and it's a name alias for "US_liquid_gallon".

```r
grep("gallon", valid_udunits()$name_singular_aliases, value=TRUE)
#> [1] "liquid_gallon, gallon"
```
