### ISSUE TITLE
mH2O

### ISSUE THREAD

**Issue by ArturIndio** [r-quantities/units#207]
Why I can not convert kgf/m^2 to mH2O? Or ftH2O to mH2O?

a<- 2
unit(a)<- "kgf/m^2"
units(a) <- with(ud_units,mH2O)
Error: cannot convert kgf/m^2 into mH2O

**Comment by Enchufa2** [comment]
Because the conversion is wrong. You are missing an "m" in the denominator: it's "kgf/m^3".

**Comment by ArturIndio** [comment]
Sorry, I want to convert pressure units. See, kgf/cm² to cmH2O or ftH2O works fine:
```
> p<- set_units(1,kgf/cm^2)
> p
1 [kgf/cm^2]
> units(p)<-"cmH2O"
> p
1000 [cmH2O]
> units(p)<-"ftH2O"
> p
32.8084 [ftH2O]
> units(p)<-"mH2O"
Error: cannot convert ftH2O into mH2O
``` 

Does mH2O means meter of water head?

**Comment by Enchufa2** [comment]
mH2O means milli-H2O, and H2O, according to the database, _specifies the acceleration at the earth's surface of a substance with the density of water_.

**Comment by ArturIndio** [comment]
How can I add manually meH20 (meters) like cmH20 (centimeters) on database? Is it possible?

**Comment by Enchufa2** [comment]
This is not a unit, but a product of units, so I recommend to treat that accordingly. These versions work fine:

```
set_units(set_units(1, "cm H2O"), "m H2O")
set_units(set_units(1, "cm*H2O"), "m*H2O")
```

**Comment by ArturIndio** [comment]
OK, but see at valid_udunits. We also have cmH2O at database so I can use cmH2O as symbolic. I would like to use meH2O (meters) as symbolic too. Of course If I use m*H2O works fine or cm*H2O.    

![image](https://user-images.githubusercontent.com/9643486/58034752-a67c7680-7afd-11e9-9acb-e1fca83c7d9d.png)

**Comment by Enchufa2** [comment]
Then, see `?install_conversion_constant`:

```r
install_conversion_constant("cmH2O", "meH2O", 0.01)
```

**Comment by ArturIndio** [comment]
Thank you for the support! That's what I would like to do.

**Comment by ArturIndio** [comment]
I suggest to include meH2O in the next package version, It's a very common unit used hydraulics.

**Comment by edzer** [comment]
@ArturIndio that should be done at [udunits-2](https://github.com/Unidata/UDUNITS-2), not in this R package.

**Comment by ArturIndio** [comment]
Hi @edzer, what I should be done? Opened the issue here or suggested the meH2O?Or both?

**Comment by edzer** [comment]
If you want to add a unit to udunits, don't add it to this R package but to the udunits-2 library it interfaces. We are not the only users of that library.

**Comment by Enchufa2** [comment]
In other words, @ArturIndio, you should open an issue in the udunits-2 repo to propose that change.

**Comment by ArturIndio** [comment]
OK, I understood. Thanks.
