### ISSUE TITLE
atan2 wrong units

### ISSUE THREAD

**Issue by glennSanders** [r-quantities/units#210]
When working with atan2 the output units are incorrect

`atan(set_units(3,mm) / set_units(4,mm))`
`0.6435011 [rad]` 
Correct units {rad]

`atan2(set_units(3,mm), set_units(4,mm))`
`0.6435011 [mm]`
Incorrect units [mm] should be [rad]

**Comment by Enchufa2** [comment]
Unfortunately, `atan2` is not S3 or S4 generic, so we cannot provide a method for it.

**Comment by glennSanders** [comment]
Thanks for your response. I will use a work-around using `atan`.

**Comment by Enchufa2** [comment]
Thanks for the report.
