### ISSUE TITLE
set_units(1, unit) and with(ud_units, unit) are not equivalent

### ISSUE THREAD

**Issue by moodymudskipper** [r-quantities/units#211]
The README says :

>The units package comes with a list of over 3000 predefined units,

```
length(ud_units)
## [1] 3248
```

Yet `ud_units$year` doesn't exist and `set_units(1, year)` works.

Could you clarify the relationship between these 2 syntaxes ?

Moreover, how can I access the list of all the spellings supported by `set_units` ? I dug into the code but I bumped into C code.

**Comment by Enchufa2** [comment]
`year` is an alias for `yr`:

```
ud_units$yr
## 1 [yr]
```

We use UDUNITS-2 as a backend, that's why you hit C code. If you want to dug into the complete list of units and aliases supported, you can check the XML files under `system.file("share/udunits", package="units")`.

**Comment by moodymudskipper** [comment]
Great thanks! I'm leaving open because in case you might want to clarify the README

**Comment by moodymudskipper** [comment]
Some things cannot be explained by those lists alone it seems, for example `set_units` accept `kiloPa` and `kPascal` but these seem to be written nowhere, is this logic in the C code ?

**Comment by Enchufa2** [comment]
Prefixes are in `udunits2-prefixes.xml`; units, in all the other files. By the way, you can also inspect the units using `units::valid_udunits()` if you have `xml2` installed.

There's the documentation of the UDUNITS2 library, which is referenced several times, so I don't think that replicating it here is a good idea. Commenting on every single unit UDUNITS2 supports does not scale up either, less so in a README.

Nevertheless, the package has two vignettes, one of which is an R Journal paper. If you think that they can be improved in any of these aspects, feedback is very welcome.

**Comment by Enchufa2** [comment]
The next version will no longer have the pre-computed `ud_units` list, which was soft-deprecated since v0.5-0. The old examples with `with(ud_units, unit)` have been updated to `make_units(unit)`.
