### ISSUE TITLE
units doesn't like bytes ?

### ISSUE THREAD

**Issue by moodymudskipper** [r-quantities/units#212]
``` r
library(units)
#> udunits system database from C:/Program Files/R/R-3.6.1/library/udunits2/share/udunits
set_units(1, MB)
#> 1 [MB]
set_units(1, kB)
#> 1 [kB]
set_units(1, MB) + set_units(1, kB)
#> Inf [MB]
```

I understand that the case might be ambiguous (1024 vs 1000) but this is a surprising output.

**Comment by Enchufa2** [comment]
`B` is not byte, but bel, like in decibels, so it's a logarithmic unit. For bytes, you have `byte` and `octet`.

**Comment by moodymudskipper** [comment]
Oh I see! thanks!
