### ISSUE TITLE
Use of isFALSE requires R>=3.5

### ISSUE THREAD

**Issue by langmm** [r-quantities/units#229]
In the recent release 0.6-6, the isFALSE function is used in `R/symbolic_units.R` which causes calls to units to fail on R < 3.5 since isFALSE was introduced in 3.5. Is your intent to no longer support older version of R or is this an error?

Either way, I am happy to create a pull request bumping the minimum support R version or removing the call to isFALSE. I am using units for the [yggdrasil](https://github.com/cropsinsilico/yggdrasil) package and noticed the error on CI jobs during a release [today](https://travis-ci.org/github/cropsinsilico/yggdrasil/builds/663192839).

**Comment by edzer** [comment]
No, that was not intentional - PR welcome!

**Comment by Enchufa2** [comment]
Ah, my fault! I was cleaning up some code, and implemented a comment. So that's why it as commented out...

**Comment by Enchufa2** [comment]
So maybe it's better to go back to the previous (ugly) version? https://github.com/r-quantities/units/commit/7104d4893baaf205131f4384d2cd5efb743cb6b0#diff-fced1b4101ae6d6ac8c90b136248b886L128

**Comment by Enchufa2** [comment]
BTW, why isn't Travis checking with oldrel?
