### ISSUE TITLE
installation of package ‘units’ had non-zero exit status

### ISSUE THREAD

**Issue by NoushinN** [r-quantities/units#231]
Hi there, any idea what's causing this error when installing units package?

`Warning in install.packages :
  installation of package ‘units’ had non-zero exit status`

**Comment by NoushinN** [comment]
It worked, installed **without** compiling

**Comment by mustafab325** [comment]
Hi,
I am new to R and facing the same issue. Could you please put down the steps you took to resolve it?

**Comment by NoushinN** [comment]
Hi @mustafab325...sure, so you can type: `install.packages("units")` in which case it starts to install the package and asks if you would like to install from source which requires compilation. The answer to that question for me had to be `no` and so it started intall in my local library. That solved the issue because if I chose `yes` then it goes the compilation with c+ route and I get an error at the end saying the package had no non-zero exit status.

It might be the way R environment is configured on our terminals...but the trick was answering `no`. Let me know if it helps

**Comment by edzer** [comment]
On windows and Mac OSX, CRAN distributes binary install of packages. If you're new to R, always use those.
