### ISSUE TITLE
unit conversion with rbind (on data.frames) 

### ISSUE THREAD

**Issue by dleutnant** [r-quantities/units#232]
Hi, 
I just came across the following issue, in which the automatic unit conversion does not apply. 
The reprex aims to `rbind` two data.frames which share the same column 'dt' of class 'units'. The unit however differs and the first one is used during `rbind`. Most probably this is rather a "rbind"-related issue but I thought it is worth sharing it here...

``` r
library(units)
#> udunits system database from /usr/local/share/udunits

# dummy data
h <- data.frame(dt = set_units(24, "h"))
min <- data.frame(dt = set_units(1440, "min"))

# binding both data.frames works, but silently gives wrong unit conversion results
# issue: first unit dominates the other 

# ... here: hour
rbind(h, min)
#>         dt
#> 1   24 [h]
#> 2 1440 [h]
# ... here: mins
rbind(min, h)
#>           dt
#> 1 1440 [min]
#> 2   24 [min]
```

<sup>Created on 2020-03-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Enchufa2** [comment]
The issue we have here is that

```r
x <- set_units(24, h)
x[2] <- set_units(1440, min)
x
#> Units: [h]
#> [1] 24 1440
```

And, more generally,

```r
x[2] <- set_units(3, m)
x
#> Units: [h]
#> [1] 24 3
```
