### ISSUE TITLE
Automatic promoting of unspecified units

### ISSUE THREAD

**Issue by mattfidler** [r-quantities/units#234]
Hi,

Is there any way you can add a feature that promotes numbers to units on operations like `+`, `-`, `==`, etc?

This way `ggplot2` should work without the `ggforce` package (which doens't work currently).  See:

https://github.com/thomasp85/ggforce/issues/190

An example would be:

```{r}
a <- set_units(1, mg) + 2
#> 3 mg
```

It seems like a design choice, so I'm unsure if you think it is a good idea or not.

**Comment by Enchufa2** [comment]
It's a design choice. Now, for convenience, we have:

```r
set_units(3, m) * 2
#> 6 [m]
```

which means that we are treating numeric vectors as unitless quantities. Under this logic, you cannot sum any unit and a unitless quantity:

```r
set_units(3, m) + set_units(2, 1)
#> Error: cannot convert 1 into m
```

Therefore, your example cannot work.
