### ISSUE TITLE
Allow restore of database

### ISSUE THREAD

**Issue by hughjonesd** [r-quantities/units#244]
Slightly related to #243, I'd like to restore the original database sometimes (e.g. on unload of a package that uses `install_` functions, or when switching between different unit "namespaces"  - e.g. in my case between LaTeX and CSS ideas about lengths). At present I can remove what I've installed but cannot easily install what I have remoced.

**Comment by Enchufa2** [comment]
Yeap, we could add a function to re-read and re-populate the database.

**Comment by Enchufa2** [comment]
Maybe even a mechanism to load external user-provided databases.
