### ISSUE TITLE
Please export ud_are_convertible()

### ISSUE THREAD

**Issue by cregouby** [r-quantities/units#258]
Hello,

In a recent [PR](https://github.com/r-lib/prettyunits/pull/28) to improve `prettyunits::pretty_num()` with support of units, I've been using the private function `units:::ud_are_convertible()`.
This makes my PR at risk for the future, and I would like to ask you to export that function in your package.

Of course adding a local pretty_num.units() function could be an alternative way-forward.

Please let me know.

**Comment by edzer** [comment]
I'm open for both options; since `prettyunits`  provides the generic it might make sense to keep the `units` method there as well.
