### ISSUE TITLE
`apply` on `units` matrix leads to loss of the `units` class

### ISSUE THREAD

**Issue by michaeldorman** [r-quantities/units#265]
When passing a `units` matrix to `apply`, the result loses the `units` class. For example:

```r
library(units)

m = set_units(matrix(1:4,2,2), m/s)                                             
## Units: [m/s]
##      [,1] [,2]
## [1,]    1    3
## [2,]    2    4 

apply(m, 1, min)                                                            
## [1] 1 2
```

It would be really convenient to keep the `units`, if possible, in colwise/rowwise operations just like in operations on the entire matrix:

```r
min(m)                                                                      
## 1 [m/s]
```

Thank you very much!

**Comment by Enchufa2** [comment]
Yeap, it would, but unfortunately there's not much we can do. This package works by implementing S3 methods for various generics. Functions like `apply` do not fall in that category, so we don't have any mechanism to make them preserve the attributes beyond wrapping them, which you can do yourself, e.g.:

```r
set_units(apply(m, 1, min), units(m), mode="standard")
```

**Comment by michaeldorman** [comment]
I understand. Thank you for the quick response and great package!
