### ISSUE TITLE
new CRAN errors

### ISSUE THREAD

**Issue by edzer** [r-quantities/units#267]
From BDR:
```
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_units.html>.

Please correct before 2021-03-06 to safely retain your package on CRAN.

The CRAN Team
```

**Comment by edzer** [comment]
With second message:
```

  if (all(!unlist(l10n_info()))) # ISO8859-15

makes no sense: l10n_info() has reported the codepage on Windows for many years and now reports (if known) the internal name of the codeset on other OSes.
```

**Comment by Enchufa2** [comment]
Makes no sense only if r-devel has changed the returned type. According to the documentation (R 4.0.3), 

```
Value:
     A list with three logical components:
    MBCS: If a multi-byte character set in use?
   UTF-8: Is this a UTF-8 locale?
 Latin-1: Is this a Latin-1 locale?
```

**Comment by edzer** [comment]
... which might be the case?

**Comment by Enchufa2** [comment]
In which case, something along the lines of "unfortunately, r-devel breaks compatibility with previous releases, and thus the following code needs to be accommodated to the new behaviour" would have been more appropriate rather than "your code makes no sense". :)

**Comment by Enchufa2** [comment]
This is the relevant change:

> (Not Windows.) l10n_info() reports an additional element, the name of the encoding as reported by the OS.

Will take a closer look and fix it ASAP.

**Comment by Enchufa2** [comment]
Interestingly enough, that code is not there anymore. So... fixed! :) I'll give another pass to the list of issues this weekend before preparing a new release. I also have to send some emails to downstream projects that use deprecated functions.
