### ISSUE TITLE
Error installing latest release.

### ISSUE THREAD

**Issue by engineerchange** [r-quantities/units#268]
```
> install.packages("units")
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/units_0.7-0.tgz'
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/units_0.7-0.tgz': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/units_0.7-0.tgz'
Warning in install.packages :
  download of package ‘units’ failed
  ```
 The CRAN link appears to 404 out; the [hyperlink](https://cran.rstudio.com/bin/macosx/contrib/4.0/units_0.7-0.tgz) in a browser doesn't work either.

**Comment by Enchufa2** [comment]
The binaries for macOS are not built yet, as the [CRAN page](https://cran.r-project.org/package=units) shows. `install.packages` should detect this and offer the installation from source as an alternative (at least, that's what happens on Windows).

Anyway, that's an R/CRAN issue, not a `units` issue. Probably the [r-sig-mac](https://stat.ethz.ch/mailman/listinfo/r-sig-mac) mailing list is a better place to report this.
