### ISSUE TITLE
units breaks on r-devel-windows-x86_64-gcc10-UCRT

### ISSUE THREAD

**Issue by edzer** [r-quantities/units#278]
See https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64-gcc10-UCRT/units-00install.html

It looks like this is the same problem as https://github.com/r-spatial/sf/issues/1629

It looks like @kalibera already addressed this, in
https://svn.r-project.org/R-dev-web/trunk/WindowsBuilds/winutf8/ucrt3/r_packages/patches/CRAN/units.diff

in which case the problem should resolve after rebuild in 24 hrs or so.

**Comment by kalibera** [comment]
Yes, the latest version already passes locally on my system.

**Comment by Enchufa2** [comment]
I suppose that we just need to add this `Makevars.ucrt` file, right? Will this patch be temporarily applied on CRAN until our next submission, or are we required to send a patch release ASAP?

**Comment by kalibera** [comment]
It is not urgent, if you integrate the patch (the `Makevars.ucrt`) into your next submission, that'd be fine. If you could then also check that there are no other issues with the package with the new toolchain, that'd be great.
