### ISSUE TITLE
`set_units(1, "s^-1") + set_units(1, "s")` should throw error

### ISSUE THREAD

**Issue by ttrikalin** [r-quantities/units#312]
There appears to be a bug when dealing with a unit and its inverse. 
```
# 1\ These evals should be FALSE but is TRUE
units::ud_are_convertible("s", "s^-1")
units::ud_are_convertible("s^2", "s^-2")
units::ud_are_convertible("m/s", "s/m")

# 2\ `+` should throw error, but returns `units` object 
# with the units of the first summand. 
# Example
units::set_units(1, "s^-1") + units::set_units(1, "s")
units::set_units(1, "s") + units::set_units(1, "s^-1")

# 3\ `*` correctly simplifies product to be dimensionless
units::set_units(1, "s") * units::set_units(1, "s^-1")
```

**Comment by Enchufa2** [comment]
This is no bug, but just reflects the design decisions made in [udunits2](https://github.com/Unidata/UDUNITS-2). As a general conversion framework, it allows you to apply any kind of (valid) conversion. For example, you could define a conversion of grams of coal into energy released when it burns. There definitely is a conversion factor (which is not the same as dimensional analysis) to convert from units to their reciprocals, and udunits2 chose to support that.

We rely on udunits2, and so we are not willing to change this philosophy. If you are not happy with this behaviour, I suggest to bring this upstream.

**Comment by ttrikalin** [comment]
Thank your replying.  
I now see in the [udunits2](https://github.com/Unidata/UDUNITS-2) code that they define a reciprocal converter and understand its behavior. 
I was using the library to implement a rudimentary dimensional analysis check. I will work around this behavior.
