### ISSUE TITLE
%% doesn't work correctly?

### ISSUE THREAD

**Issue by edzer** [r-quantities/units#313]
This doesn't seem right:
```r
> set_units(1.98, m) %% set_units(1, foot)
0.98 [m]
> set_units(1.98, m) %% set_units(set_units(1, foot), m)
0.1512 [m]
```

**Comment by Enchufa2** [comment]
You mean the first or the second one?

**Comment by Enchufa2** [comment]
These three should be the same, right?

``` r
library(units)
#> udunits database from /usr/share/udunits/udunits2.xml
x <- set_units(1.98, m)
y <- set_units(1, foot)
x %% y
#> 0.98 [m]
x %% set_units(y, m)
#> 0.1512 [m]
drop_units(x) %% drop_units(set_units(y, m))
#> [1] 0.1512
```

**Comment by edzer** [comment]
Yes, I think so.

**Comment by edzer** [comment]
units. I tried to compute my length in feet and inches:
```r
> library(units)
udunits database from /usr/share/xml/udunits/udunits2.xml
> set_units(1.98, m) %/% set_units(set_units(1, foot), m)
6 [1]
> rem = set_units(1.98, m) %% set_units(set_units(1, foot), m)
> set_units(rem, `in`)
5.952756 [in]
```
however this also seems wrong:
```r
> set_units(1.98, m) %/% set_units(1, foot)
3.28084 [1]
```

**Comment by Enchufa2** [comment]
Mmmmh, I think `/`, `%/%` and `%%` should agree on units. Like this (which is not the current behaviour):

``` r
set_units(1.98, m) / set_units(1, m)
#> 1.98 [1]
set_units(1.98, m) %/% set_units(1, m)
#> 1 [1]
set_units(1.98, m) %% set_units(1, m)
#> 0.98 [1]
set_units(1.98, m) / 1
#> 1.98 [m]
set_units(1.98, m) %/% 1
#> 1 [m]
set_units(1.98, m) %% 1
#> 0.98 [m]
```

In other words, this:

```r
x / y == x %/% y + x %% y
```

should be `TRUE` regardless of the units.

**Comment by Enchufa2** [comment]
Forget about my previous comment, deleted now. You are right. This should be always true:

```r
x == y * (x %/% y) + x %% y
```

**Comment by Enchufa2** [comment]
This doesn't work properly either:

``` r
x <- set_units(3, m)
y <- set_units(1.4, foot)
x %/% y
#> 6.56168 [1]
```

**Comment by gancao** [comment]
Did anyone install units successfully? If so, could you please share the installed package with me? would appreciate it very much
 I could not install it successfully and I have tried many ways

**Comment by edzer** [comment]
```r
library(units)
# udunits database from /usr/share/xml/udunits/udunits2.xml
x <- set_units(3, m)
y <- set_units(1.4, foot)
x %/% y
# 7 [1]
ym = set_units(y, m)
x %/% y
# 7 [1]
x
# 3 [m]
y
# 1.4 [foot]
x %/% ym
# 7 [1]
x
# 3 [m]
ym
# 0.42672 [m]
ym * (x %/% ym) + (x %% ym)
# 3 [m]
set_units(y * (x %/% y) + (x %% y), m)
# 3 [m]
```

**Comment by edzer** [comment]
This now breaks on [the tests](https://github.com/r-quantities/units/actions/runs/3608146942/jobs/6080586541#step:9:180), with
```r
  > a = set_units(1:5, m)
  > a %/% a
  Units: [1]
  [1] 1 1 1 1 1
  > a %/% set_units(2)
  Error: cannot convert 1 into m
```
but my feeling is that that is correct, and needs removed from the tests.

**Comment by Enchufa2** [comment]
Hmmm... That example may not be the best one, but it should work. The commit above improves things a little bit for a particular case (convertible units), but these operations should work, in principle, with any combination of units. 

I worked a bit on this problem some weeks ago, but I entered a rabbit hole at some point and undid the work. What I have is a small test script of things that _should_ work:

```r
library(units)
x <- set_units(3, m^2)
y <- set_units(1.4, foot)
x %/% y

drop_units(x) %% drop_units(set_units(y, m))
x %% y
x %% set_units(y, m)
x %% drop_units(set_units(y, m))
x %% set_units(drop_units(set_units(y, m)), 1)
x %% set_units(drop_units(set_units(y, m)), 1)
drop_units(x) %% set_units(y, m) # error

drop_units(set_units(x, foot)) %% drop_units(y)
set_units(x, foot) %% y
set_units(x, foot) %% set_units(y, m)
set_units(x, foot) %% drop_units(y)
set_units(x, foot) %% set_units(drop_units(y), 1)
drop_units(set_units(x, foot)) %% y # error

all.equal(x, y * (x %/% y) + x %% y)
```

We could:

1. roll an update with aa387a1, but then I would revert 7622f33, and we would need to remove that example to avoid the check error for now;
2. or revert both aa387a1, 7622f33 and aim at a complete solution to this bug for a future release.

**Comment by edzer** [comment]
> these operations should work, in principle, with any combination of units.

I don't think that `%/%` or `%%` should work for incompatible units.

**Comment by Enchufa2** [comment]
You can put

```r
set_units(1, foot) / set_units(1, m^2)
#> 0.3048 [1/m]
```

So the same for `%/%` and `%%`. They're just the integer and remainder of the operation above.

**Comment by edzer** [comment]
Feels odd, but please go ahead (fixing this or reverting my change).

**Comment by Enchufa2** [comment]
My previous attempt at this tried to make conversions and forward with NextMethod, but I think that the most sensible thing to do is to perform a regular division and extract the proper part afterwards. Let me try.

**Comment by Enchufa2** [comment]
Admittedly not the most efficient implementation, but it works. :) I've added the test cases above to the test suite.

**Comment by Enchufa2** [comment]
Package quantities fail with this change a couple of tests. I'll take a look, they probably need to be removed. In such a case, I need to send an update to CRAN too. I'll run full revdep checks too just in case.

**Comment by Enchufa2** [comment]
It required the same fix in package errors. Let me know when you plan to send the update to CRAN, and I'll send an update for errors and quantities too.

**Comment by edzer** [comment]
I'm ready to go. Shall I inform CRAN that breakage is expected in pkg `errors` and `quantities`, or do you want to submit them first?

**Comment by Enchufa2** [comment]
Yes, please, submit informing about the expected breakage. I'll submit in a few hours to when I come back to my laptop. Thanks!
