### ISSUE TITLE
Valgrind Issues

### ISSUE THREAD

**Issue by billdenney** [r-quantities/units#315]
While working in a different package that depends on the units library, we were running valgrind, and we got many errors that were due to libudunits2.  I'm not sure, but I'd guess that most of these are related to issues in the parent UDUNITS2 library, but I thought it best to report the issue where I find it.  I've attached the file generated when I run the following in Linux:

```
R -d "valgrind --tool=memcheck --leak-check=full" \
            -e "devtools::load_all();devtools::test()" 2>&1 | \
            tee ../units_test_valgrind.txt
```

[units_test_valgrind.txt](https://github.com/r-quantities/units/files/8422848/units_test_valgrind.txt)

Can you tell if these are issues in the units library or UDUNITS2 or something else?

**Comment by Enchufa2** [comment]
This is an upstream issue. Our check results on CRAN are clean (which possibly filter out issues in the shared library).

**Comment by billdenney** [comment]
Thanks for confirming that it isn't `unuts`.
