### ISSUE TITLE
share the units package

### ISSUE THREAD

**Issue by gancao** [r-quantities/units#316]
Did anyone install units successfully? If so, could you please share the installed package with me? would appreciate it very much

**Comment by Enchufa2** [comment]
Sorry, but this is not the way to ask for help. If you have an installation issue, and you have a reasonable suspicion that there could be an issue in the package, then you would need to provide all the details required for us to debug it. If you need general help about package installation, read the manual page for `install.packages` first, then I recommend the [R-help](https://stat.ethz.ch/mailman/listinfo/r-help) mailing list, where, again, you would need to provide all the details of your issue (such as the operating system, the version of R, the output from `sessionInfo()`, the version of the package you are trying to install, and the error message you get).
