### ISSUE TITLE
Incorrect square foot to acre conversion

### ISSUE THREAD

**Issue by iembry** [r-quantities/units#317]
Hi, I'm using `units` version 0.8-0 and I have come across the following incorrect conversion:

`ft2 <- set_units(43560, ft ^ 2)`

`acre <- ft2`

`units(acre) <- make_units(acre)`

`0.999996 [acre]`

According to the [UDUNITS-2 database](https://www.unidata.ucar.edu/software/udunits/udunits-2.2.28/udunits2-common.xml), an acre is "unit of area in the US Customary System, used in land and sea floor measurement, equal to 43560 square feet".

Please correct the conversion error.

Thank you.

Irucka

**Comment by edzer** [comment]
```r
> set_units(1, acre) |> set_units(foot^2)
43560.17 [foot^2]
```
The R `units` package _uses_ the C udunits library, but doesn't define it. If you believe this is an error, you need to report it upstream.

**Comment by edzer** [comment]
For instance, the `udunits2` command line tool gives
```
$ udunits2
You have: 1 acre
You want: foot^2
    1 acre = 43560.2 foot^2
    x/foot^2 = 43560.2*(x/acre)
```
(and seems to round to 6 digits)

**Comment by Enchufa2** [comment]
@iembry The conversion is fine. You just didn't use the proper foot.

``` r
ft2 <- set_units(43560, US_survey_foot ^ 2)
acre <- ft2
units(acre) <- make_units(acre)
acre
#> 1 [acre]

set_units(as_units("US_survey_foot"), foot)
#> 1.000002 [foot]
```

¯\_(ツ)_/¯

**Comment by iembry** [comment]
@ Enchufa2  Thank you for your suggestion! I'll use the proper foot unit.
