### ISSUE TITLE
Invitation to attend the Units Summit at SciDataCon 2022

### ISSUE THREAD

**Issue by edzer** [r-quantities/units#320]
I received the following invitation, but am afraid that I can't follow up on it:

Greetings from the CODATA Digital Representation of Units of Measurement (DRUM) Task Group!

Each of you has been identified as a point of contact for a digital unit representation system (if you are not the correct person for please forward this message).  The DRUM Task Group would like to invite you to attend the upcoming Units Summit to be held as part of SciDataCon 2022 (part of [International Data Week](https://internationaldataweek.org/) IDW).  For more information about the summit go to https://codata.org/initiatives/task-groups/drum/units-summit-recap-meeting/.  Note, [paid registration](https://idw2022.org/bbs/content.php?co_id=regist_process_en&lang=English) is required to IDW.

Specifically, I would like to invite you to session 449 on ['Digital Unit Representation Systems and their Use in Infrastructure](https://www.scidatacon.org/IDW-2022/sessions/449/)' which will be held June 21st at 00:30-02:00 UTC. As the timing of the session (determined by the Korean hosts of IDW) is not conducive to many time zones I thought it important to provide each of you the opportunity to present a little about your digital units representation system.  I therefore invite you to provide me with a link to a short (5-10 min) video describing your system by June 7th.  I will then make these links available to participants in the session on June 8th. I realize that the timing of this email and request is relatively short but I thought it important to reach out prior to the session so that as many as possible of you can participate.

I also invite you provide feedback to the following questions, the answers of which will be summarized at the session and used in part to drive the panel discussion.
1. What need(s) does your unit of representation system solve? (If you can include also the community(ies) it supports that would be appreciated)
2. What are the pain points you have encountered while implementing your system?
3. What infrastructure or services would be most helpful in developing your system and/or supporting your communities relative to units of measurement?

I would also like to make you aware the at the DRUM TG along with the CIPM Expert Group on the Digital SI recently published an opinion paper in Nature as a ‘[Call to Action](https://doi.org/10.1038/d41586-022-01233-w)’ on digital unit representation.  We hope this paper sparks a movement toward increased interoperability of units in digital systems which in turn increases the interoperability of data in a [FAIR](https://www.go-fair.org/fair-principles/) way. Finally, mark your calendar that Friday May 20th is [World Metrology Day](https://www.worldmetrologyday.org/)!

I hope you can participate and if you have any questions please contact me.

Regards,
Stuart Chalk
SciDataCon Session 449 Organizer
CODATA DRUM Secretary
CIPM DSI Expert Group Member

(contact details)

Please let me know if someone wants to follow up!

**Comment by Enchufa2** [comment]
I very much would like to follow up on this, but unfortunately too short notice for me. Too many things on my plate already. :(
