### ISSUE TITLE
Becquerels Show as Hertz

### ISSUE THREAD

**Issue by tombishop1** [r-quantities/units#325]
When attempting to assign the units `Bq`, they are only recognised as `Hz`. I'm guessing this is because they share the same `def`, `1/s`, as they are both measurements of frequency, but they do have subtly different definitions.

> set_units(1:5, "Bq")
Units: [Hz]
[1] 1 2 3 4 5

**Comment by Enchufa2** [comment]
Unfortunately, this is how udunits2 works. E.g., with the thinnest wrapper we have around parsing and formatting,

```r
> units:::R_ut_format(units:::R_ut_parse("Bq"))
[1] "Hz"
```

And this is because Bq is defined as an alias of 1/s, which is already assigned to Hz. You could bring this issue upstream.

**Comment by tombishop1** [comment]
Understood, I'll look at the options there. Is there a hack to remove one of entries (e.g. delete `Hz`) for the duration of a session?

**Comment by tombishop1** [comment]
Yes, that works for me too, so I guess we can close this for now, and perhaps I'll open an issue upstream. Inspecting `udunits2-derived.xml`, there is a special entry for "SI derived units with special names and symbols admitted for reasons of safeguarding human health", containing Bq, Gy and Sv. The entry for Bq contains a comment that it is "an alias because 1/s is already mapped to Hz". I'm guessing `udunits2` is converting from the alias without considering the exception for human health.
