### ISSUE TITLE
Unitless quantitities and functions (particularly exp)

### ISSUE THREAD

**Issue by chrisbrunsdon** [r-quantities/units#328]
Although under many circumstances, functions like sin(), exp() are not meaningful for arguments with units,  they are if the arguments are the result of an expression involving units that is itself unitless.  However,  this sometimes leads to issues:

```
library(units)
x <- set_units(1,'m')
y <- set_units(2,'m')
exp(x/y)
```

gives an error, and 
```
sin(x/y)
```
gives a warning: "In Math.units(x/y) : Operation sin not meaningful for units"
However I think both expressions are well defined.   The error actually breaks things,  however I still think the warning in the situation where the expression is unitless is not appropriate because although the operation is not meaningful for units,  in this expression the argument has no units.

Thanks for considering.

**Comment by Enchufa2** [comment]
Thanks. In the first case, that's an unexpected error, so there's some bug. In the second case, we could treat this as radians.

**Comment by chrisbrunsdon** [comment]
Thanks for the reply.   And apologies,  the second issue was an oversight on my part - if I enter for example:
x <- set_units(pi/2,'rad')
sin(x)
then I get no warning,  and the units of the result are '1' - ie unitless.   That issue was down to my misunderstanding - thanks for putting me right!
Chris

**Comment by Enchufa2** [comment]
My point was that this currently raises a warning:

```r
> x <- set_units(3, m)/set_units(2, m)
> sin(x)
[1] 0.997495
Warning message:
In Math.units(set_units(3, m)/set_units(2, m)) :
  Operation sin not meaningful for units
```

But this doesn't:

```r
> sin(set_units(x, rad))
0.997495 [1]
```

So the question is should we try to convert to radians the argument of any trigonometric call, or should this be done explicitly by the user.

**Comment by edzer** [comment]
I think that warning should disappear, and the implicit assumption that unitless implies radians is good, just as with `sin(3/2)`.

**Comment by edzer** [comment]
We already _convert_ to radians:
```r
> sin(set_units(3, degree))
0.05233596 [1]
> sin(set_units(3, rad))
0.14112 [1]
```
but we don't _cast_ to radians in case of unitless.

**Comment by Enchufa2** [comment]
> but we don't _cast_ to radians in case of unitless.

Yes, that's what I meant, thanks for pointing this out.

**Comment by CGMossa** [comment]
Even this is a problem:
```r
> exp(set_units(1, 1))
Error in if (length(u$numerator) > 1 || !grepl("\\(re", u$numerator) ||  : 
  missing value where TRUE/FALSE needed
 ```
