### ISSUE TITLE
vignette MathJax

### ISSUE THREAD

**Issue by babayoshihiko** [r-quantities/units#329]
Math expressions are not rendered:
https://cran.r-project.org/web/packages/units/vignettes/measurement_units_in_R.html

Perhaps, the line 19 in measurement_units_in_R.Rmd is not necessary:
`<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML" type="text/javascript"></script>`

Removing the line renders the expressions, but does not render e acute/grave in line 110, though.

**Comment by edzer** [comment]
Thanks for reporting!
