### ISSUE TITLE
Compatibility between `units` and `errors` library

### ISSUE THREAD

**Issue by ekatko1** [r-quantities/units#330]
I'm not sure which library this should should be an issue with, but it would be great to have numbers with both units and errors:

```
set_errors( set_units(5, g) )
``` 
currently, this operation is giving me the following error:

```
Error in UseMethod("set_errors") : 
  no applicable method for 'set_errors' applied to an object of class "units"
```

**Comment by edzer** [comment]
That's what the package "quantities" was developed for.

**Comment by Enchufa2** [comment]
We have:

``` r
library(quantities)
#> Loading required package: units
#> udunits database from /usr/share/udunits/udunits2.xml
#> Loading required package: errors

set_errors(set_units(5, g), 0.1)
#> 5.0(1) [g]
```

See the [project page](https://r-quantities.github.io/quantities/) for further details.

**Comment by ekatko1** [comment]
Oh I see now, thank you so much!!
Egor
