### ISSUE TITLE
Unit says that it is already present when it has been removed

### ISSUE THREAD

**Issue by billdenney** [r-quantities/units#334]
Related to #299

In the code below, it says that Eq_ammonia already exists and maps to mol_ammonia, even though I'm specifically removing it before starting.  Any ideas why Eq_ammonia already exists when I've explicitly removed it?

``` r
library(units)
#> udunits database from C:/Users/wdenn/AppData/Local/R/win-library/4.2/units/share/udunits/udunits2.xml
# make sure that nothing is there
units::remove_unit(c("g_ammonia", "mol_ammonia", "Eq_ammonia"))
units::install_unit("g_ammonia")
units::install_unit("mol_ammonia", def = "17.031 g_ammonia")
units::install_unit("Eq_ammonia", def = "1 mol_ammonia")
#> Error in ud_map_symbols(symbol, ut_unit): Unit already maps to "mol_ammonia"
```

<sup>Created on 2022-12-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by Enchufa2** [comment]
Yes, the thing is that a unit can only be mapped to one symbol. So if you wanted to have aliases for that unit, you should call

```r
units::install_unit(c("mol_ammonia", "Eq_ammonia"), def = "17.031 g_ammonia")
```

**Comment by billdenney** [comment]
Thanks!

I have some units where they don't map identically (in that other case, 1 mol = 0.5 Eq), so that I or others know how to do it, you can always map back to the original unit, it seems:

```
units::remove_unit(c("g_ammonia", "mol_ammonia", "Eq_ammonia"))
units::install_unit("g_ammonia")
units::install_unit("mol_ammonia", def = "17.031 g_ammonia")
units::install_unit("Eq_ammonia", def = "10 g_ammonia")
```

**Comment by Enchufa2** [comment]
Not only the original unit. This works too:

```r
units::install_unit("g_ammonia")
units::install_unit("mol_ammonia", def = "17.031 g_ammonia")
units::install_unit("Eq_ammonia", def = "10/17.031 mol_ammonia")
```

The issue above was trying to redefine a unit with another symbol.
