### ISSUE TITLE
udunits2 cannot load UTF-16 paths on Windows

### ISSUE THREAD

**Issue by dite0843** [r-quantities/units#342]
library(units)
Error: package or namespace load failed for ‘units’:
 .onLoad failed in loadNamespace() for 'units', details:
  call: NULL
  error: no database found!

I already installed the package, how do I solve this?
Thanks in advance.

**Comment by Enchufa2** [comment]
We would need more info. How did you install the package? Was it from CRAN? What's the operating system?

**Comment by edzer** [comment]
Please remove the package with `remove.packages("units")`, then report the exact output you see after `install.packages("units")`, and after `library(units)`.

**Comment by dite0843** [comment]
Here it is, 
This one is after the install.package function

install.packages("units")
 Installing package into ‘C:/Users/พิชญาเนตร คำหม้อ/AppData/Local/R/win-library/4.2’ (as ‘lib’ is unspecified)
 trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/units_0.8-1.zip' Content type 'application/zip' length 1392004 bytes (1.3 MB) downloaded 1.3 MB  package ‘units’ successfully unpacked and MD5 sums checked  The downloaded binary packages are in 	C:\Users\พิชญาเนตร คำหม้อ\AppData\Local\Temp\RtmpQnGkNS\downloaded_packages

and after the library function,

library(units) 
Error: package or namespace load failed for ‘units’:  
.onLoad failed in loadNamespace() for 'units', details:   call: NULL   
error: no database found!




> Please remove the package with `remove.packages("units")`, then report the exact output you see after `install.packages("units")`, and after `library(units)`.

**Comment by Enchufa2** [comment]
Oh, your user name... That's most probably UTF-16, and I don't think that's supported (not sure if this is an R limitation, or a limitation in the udunits2 library), but either way there's nothing we can do from the units package. My recommendation would be to set you user library in a different path, outside of your user directory.

**Comment by edzer** [comment]
The issue might be white spaces in the library path; try one without.

**Comment by Enchufa2** [comment]
Sharp eye! Didn't see the space in there. It certainly could be that. But more importantly this is something we can test. :)

**Comment by edzer** [comment]
[R for windows FAQ 2.15](https://cran.r-project.org/bin/windows/base/rw-FAQ.html#R-can_0027t-find-my-file)

**Comment by Enchufa2** [comment]
But we do not specify the path in any problematic way, we just rely on `system.file` [here](https://github.com/r-quantities/units/blob/e51bf61eb4a115ad1e4f066a6e91b83914eae751/R/database.R#L12). So either `system.file` does not retrieve the path correctly (maybe due to a compatibillity issue with UTF-16), or the retrieved path is correct and udunits2 is not able to follow it. Maybe this is a question for r-package-devel.

**Comment by Enchufa2** [comment]
This is a Windows 10 machine:

```r
> x <- "C:\\Users\\aulavirtual\\Documents\\พิชญาเนตร คำหม้อ\\udunits2.xml"
> file.exists(x)
[1] TRUE
> units:::ud_init(x)
Error in units:::ud_init(x) : no database found!
> shortPathName(x)
[1] "C:\\Users\\AULAVI~1\\DOCUME~1\\01C4~1\\udunits2.xml"
> units:::ud_init(shortPathName(x))
```

This confirms that is a lack of support in udunits2. But it seems that a conditional call to `shortPathName()` should fix this.

**Comment by dite0843** [comment]
Thanks to all for the solution!

I solved it by changing the packages folder to other part that doesn’t have any Thai in it, and it works!
