### ISSUE TITLE
support for scale_*_reverse()

### ISSUE THREAD

**Issue by jkeuskamp** [r-quantities/units#343]
A feature request rather than a bug:
Units facilitates the usage of ggplot with units rather seamlessly.
A small shortcoming is the usage of `scale_*_reverse()`. This fails with
```
Error in Ops.units(x, range[1]) : 
  both operands of the expression should be "units" objects
```
because `scale_*_reverse()` calls `scale_y_continuous(trans = scales::reverse_trans())` to invert the axis. 
It would be convenient if `scale_*_reverse()` would call `scale_y_units(trans = scales::reverse_trans())` when applicable.

**Comment by Enchufa2** [comment]
But this works fine:

```r
library(units)

mtcars$consumption <- set_units(mtcars$mpg, mi / gallon)
mtcars$power <- set_units(mtcars$hp, hp)

# Use units encoded into the data
ggplot(mtcars) +
  geom_point(aes(power, consumption))

# Convert units on the fly during plotting
ggplot(mtcars) +
  geom_point(aes(power, consumption)) +
  scale_x_units(unit = "W", trans="reverse")
```

So I'm not sure what are you proposing exactly.

**Comment by jkeuskamp** [comment]
It does indeed but takes some digging, but it would be more convenient if units would support all ggplot varieties of scale_*_continous. I agree it is not a very pressing issue though 👍

**Comment by Enchufa2** [comment]
So you propose having `scale_x_units_reverse`, `scale_x_units_log10` and so on?

**Comment by jkeuskamp** [comment]
I would propose to edit the documentation of scale_*_units to say that the transformation convenience functions included with ggplot (scale_*_log10()⁠, ⁠ scale_*_sqrt()⁠, scale_*_reverse()⁠, are not supported and include an example like:

# transform axes using the trans argument
ggplot(mtcars) +
  geom_point(aes(power, 1 / consumption)) +
scale_y_units(trans= reverse_trans())
}

From: Iñaki Ucar ***@***.***>
Date: Friday, 24 February 2023 at 10:34
To: r-quantities/units ***@***.***>
Cc: Keuskamp, J.A. (Joost) ***@***.***>, Author ***@***.***>
Subject: Re: [r-quantities/units] support for scale_*_reverse() (Issue #343)

So you propose having scale_x_units_reverse, scale_x_units_log10 and so on?
