### ISSUE TITLE
Allow sprintf.units?

### ISSUE THREAD

**Issue by hughjonesd** [r-quantities/units#345]
I wonder if you'd consider a `sprintf.units` method, analogous to `format.units`. At the moment, it works but the unit is dropped:

```r
x <- set_units(1:3, "m/s") x
> sprintf("%.3f", x)
[1] "1.000" "2.000" "3.000"
```

**Comment by Enchufa2** [comment]
Is that possible? I don't think this is S3 generic.

**Comment by hughjonesd** [comment]
Ah. In that case, never mind - my mistake.
