### ISSUE TITLE
Adding molarity?

### ISSUE THREAD

**Issue by sardnar** [r-quantities/units#362]
Hi, 
Thank you for this cool work. I have a request for adding molarity units. molarity is a chemical unit for concentration. 1M = mol/L. 1uM = 1micro mol /L ... etc. I think this could be applied by the symbols of M, mM, uM, nM ... etc.

A tough part however is that moles is a standardized quantity of weight by molecular mass. So 1 mol of calcium = 40 gms. 

Is some extension like that possible?

**Comment by Enchufa2** [comment]
We rely on udunits2, and molarity is not defined in that database, but we provide a mechanism to extend the database with new units. In this case, you need:

```r
install_unit("M", "1 mol/L", "molarity")
```

and you are good to go.

About moles of substances, it's a complicated problem, yes. There's an ongoing effort to address this in a separate package, see https://github.com/r-quantities/substances/issues/1.

**Comment by sardnar** [comment]
Thanks! When I follow this discussions, I can find a talk about `install_conversion_constant()` function in units package. However, I can't find it exported?

**Comment by Enchufa2** [comment]
That's an old function, long gone. `install_unit` is the replacement.
