### ISSUE TITLE
nonconvertible units are shown as "convertible"

### ISSUE THREAD

**Issue by lschneiderbauer** [r-quantities/units#379]
I must be a little more annoying.

Maybe I am misunderstanding what "two units being convertible into each other" in this package means, but to me it seems correct to say "quantity measured in unit A is convertible to quantity measured in unit B" if the quantities describe the same physical concept. That can be simply different scales of the same unit (milli-, kilo-,...), but also different unit definitions of the same physical concept, like meter and feet (length). Or Pascal and Bar (pressure). Etc.

What does not fall into that category is the inversion of a unit: second and 1/second do not describe the same physical concepts (one is time, the other is a frequency), and so these are not "convertible". 

In this sense, the following result seems odd to me: `units::ud_are_convertible()` says that seconds are convertible to Hertz.
In general it seems, all units are convertible to its inverse unit (if you trust units::ud_are_convertible()). This seems wrong to me.

``` r
# units 0.8-5.7
library(units)
#> udunits database from /usr/share/xml/udunits/udunits2.xml

x <- set_units(1, "s")
y <- set_units(1, "Hz")
z <- set_units(1, "1/s")

ud_are_convertible(units(x), units(y))
#> [1] TRUE
ud_are_convertible(units(x), units(z))
#> [1] TRUE
```

<sup>Created on 2024-12-29 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by Enchufa2** [comment]
It is what it is. This is how udunits2 works. And we rely on it, so:

```r
> set_units(set_units(440, Hz), s)
0.002272727 [s]
```

Technically, they *are* convertible. 440 cycles per second are 0.00227 seconds per cycle. udunits2, and units by extension, deals with units, not with physical concepts. That's another layer of abstraction that you are adding and goes beyond the scope of this package.

There was a simplification function that used `ud_are_convertible` in the wrong way, and that led to #378, now fixed. But this is a non-issue, it's just how udunits2 works.
