### ISSUE TITLE
Pull request opportunities (flexible unit parsing, simpler function interface)

### ISSUE THREAD

**Issue by ezwelty** [r-quantities/units#45]
Thanks for bringing unit documentation and conversion to life in R with this wonderful package. I've been using it extensively for some heavy data parsing, and through that process, ended up building my own wrapper around the package. That is described in detail here:

https://github.com/ezwelty/units2

Now, I would love to incorporate some of the functionality I developed back into `units`, but figured it was best to bring it up for discussion before slapping some pull requests around. I look forward to your thoughts.

### `units2::parse_unit` (vs. `units::parse_unit`)

  1. Supports product power form, arithmetic expressions, and any combination thereof.
  2. Correctly handles units with numbers in their names.
  3. `units::parse_unit` silently creates new units, which was dangerous for automation from unknown inputs. My version throws an error, but I could see adding an argument to control the behavior.
  4. A "side effect" of the parsing approached used by `units2::parse_unit` (evaluating against `units::ud_units`) is that it replaces unit names with their corresponding symbols. This is the behavior I wanted, as otherwise, it is hard to know whether the unit name was actually correctly recognized. But this could be addressed for example by adding a corresponding `units::ud_units_synonyms` to fallback on, which would also make unit names more transparent for users.

### `units2::deparse_unit` (vs. `units::as_cf`)

Renamed for symmetry with `parse_unit`. I could never remember "as_cf".

### `units2::as_units` & `units2::convert_units` (vs. `units::as.units` & `units::set_units`)

As opposed to their `units` equivalents, these allow either string or units objects as unit specification, for somewhat more compact coercion and conversion syntax:

```{r}
library(magrittr)
x <- 1:10
from <- "meters s-1"
to <- "km hour-1"
# units
x %>%
  units::as.units(value = units::parse_unit(from)) %>%
  units::set_units(value = units::parse_unit(to))
# units2 equivalent
x %>%
  units2::convert_units(from = from, to = to)
# or
x %>%
  units2::as_units(from) %>%
  units2::as_units(to)
```

With `units2::parse_unit` supporting arithmetic expression in string form, I dropped the non-standard evaluation in `units::set_units` to avoid dangerous and/or confusing behavior:

```{r}
units2::as_units(x, "meters/s")
units::set_units(x, meters/s)
meters <- 0.01
units::set_units(x, meters/s)
```

With string input, things always work the same way:

```
units::as.units(x, m/s) # does not work
units::set_units(x, m/s) # works
units::set_units(x, °/s) # does not work
units::set_units(x, `°`/s) # works
units2::as_units(x, "m/s") # always works the same way
units2::as_units(x, "°/s")
```

**Comment by edzer** [comment]
Lots of great ideas! I like most of them, but will not have time to get to this before September.

There's some tension between being user-friendly and being strict, and both have their advantages; I can see room for a global option to control this.

**Comment by edzer** [comment]
About the problem that
```r
units::set_units(x, meters/s)
```
works differently depending on whether e.g.
```r
meters <- 0.01
```
precedes it, I suggest that we change the order of evaluating arguments:

1. look up in `names(ud_units)`
2. try udunits2 (ud.is.symbol, ud.is.parseable)
3. try parent.frame()

this should simply ignore a value for `meters` set e.g. in `.GlobalEnv`; we could even warn for the case there is ambiguity (but still choose for the udunits value). This procedure should be non-ambiguous and rule out a lot of nonsense.

The ability of `units2` to parse a string like `"m/s"` is something we need to port to `units`.

I think enforcing string definitions is too user-unfriendly; NSE is here to stay. Comments?

**Comment by ezwelty** [comment]
If the argument is a variable in the parent frame containing the units as a character vector, the user will be expecting that string to be parsed and used, not the name of the variable, which is what would happen in the order you proposed if the variable name matched any of the supported units. This is already a problem with the current version:

```
u <- "m"
units::set_units(1, u)
```
> 1 u

The procedure could be amended to try parent.frame() and use a local variable value first if it contains a parseable unit string. This might look like:

1. If character, parse with `parse_unit`, or if units, use directly.
2. If in parent.frame(), use value (see 1).
3. Either way, capture argument as string and parse with `parse_unit`.

If 1 or 2 yield a valid result, throw warning if result from 3 was valid and different. If 1 or 2 don't apply, return result from 3. `parse_unit` is probably where all the unit name matching should happen (that's how I have `units2::parse_unit`).

p.s. I'm a fan of NSE but the list of unit symbols and their synonyms is vast and not under the user's control (unlike, say, a data.frame), hence the danger NSE presents here.

**Comment by edzer** [comment]
Sounds like a solid plan!

**Comment by edzer** [comment]
See [here](https://github.com/edzer/units/blob/master/tests/set_units.Rout.save), copied below:

<details>

```r
> library(units)

Attaching package: ‘units’

The following object is masked from ‘package:base’:

    %*%

> library(testthat)
> 
> ref = set_units(1, m)
> 
> # character input
> expect_equal(set_units(1, "m"), ref)
> # units input
> expect_equal(set_units(1, make_unit("m")), ref)
> # symbolic_units input
> expect_equal(set_units(1, units(ref)), ref)
> 
> set_units(1, m/s)
1 m/s
> 
> # use object from parent frame, non-ambiguous:
> foo = ref
> expect_equal(set_units(1, foo), ref)
> foo = "m"
> expect_equal(set_units(1, foo), ref)
> foo = make_unit("m")
> expect_equal(set_units(1, foo), ref)
> 
> # ambiguous, should warn:
> m = "u"
> set_units(1, m) # m by NSE
1 m
Warning message:
ambiguous argument: m is interpreted by its name, not by its value 
> m = make_unit("u")
> set_units(1, m) # m by NSE
1 m
> 
> degree_C = "m"
> set_units(1, degree_C)
1 °C
Warning message:
ambiguous argument: degree_C is interpreted by its name, not by its value 
> 
> degree_C = make_unit("m")
> (dc <- set_units(1, degree_C))
1 °C
> 
> degree_C = units(dc)
> set_units(1, degree_C)
1 °C
> 
> # OK:
> set_units(1, "bar")
1 bar
> (tenbar <- set_units(10, bar))
10 bar
> (set_units(1, units(tenbar)))
1 bar
> (set_units(1, tenbar))
10 bar
> 
> # still worrying:
> set_units(1, units(degree_C))
1 units(degree_C)
> udunits2::ud.is.parseable("units(degree_C)")
[1] TRUE
> # no warning, because units(degree_C) does not eval
> set_units(1, units(m))
1 units(m)
> udunits2::ud.is.parseable("units(m)")
[1] TRUE
> set_units(10, uu <- degree_C)
10 °C
> 
```
</details>

I think this solves the evaluation order and makes it unambiguous. Parsing still to do.

**Comment by edzer** [comment]
(comment above updated)

**Comment by edzer** [comment]
I now see this regression (note the name):
```r
> data.frame(z = set_units(1, m))
    x
1 1 m
```

**Comment by edzer** [comment]
The regression was removed by removing `as.data.frame.units`.

details section in comment above updated after https://github.com/edzer/units/commit/40cbbd60a2a75f82c735df28a6866a21e1d92bfa

**Comment by Enchufa2** [comment]
Closing this, as it is quite outdated. Feel free to comment if there's still something we should consider.
