### ISSUE TITLE
Consider automating udunits installation?

### ISSUE THREAD

**Issue by kendonB** [r-quantities/units#55]
I am on RHEL6.3 (no root access) and it seems like my only option to install udunits is to install from source.

System requirements seem like a barrier to reproducibility that would be nice to overcome. I imagine automating this would encourage some adoption of ``units`` and ``sf`` . 

Is this even possible?

**Comment by edzer** [comment]
Yes, you may have to juggle with `-L` configuration flags, and setting environment variable `LD_LIBRARY_PATH`. Thinking about `sf`: how do you deal with gdal, geos and proj external dependencies?

Thinking about reproducibility: are you allowed to build & start a docker container on the system?

**Comment by kendonB** [comment]
gdal, geos, and proj seem to come built into the cluster. I would have guessed any well run scientific computing cluster would have those three.

FYI, I posted my hacky solution in https://github.com/edzer/units/issues/1

**Comment by kendonB** [comment]
Also to answer your question about docker containers, I can't see why this wouldn't work and I haven't seen anything which says it's not allowed. However, I'm personally comfortable assuming that the reproducer has R on one of the major platforms and is able to install the R packages necessary to build the project and is able to run my project building script.

**Comment by billdenney** [comment]
I think that this is resolved with 0.6.0 including udunits in its source.  (Though I'm not sure.)
