### ISSUE TITLE
make_units2() and .udunits_symbols_info()

### ISSUE THREAD

**Issue by t-kalinowski** [r-quantities/units#60]
Hello,

As part of a project I recently built something ontop of the `units` package, and in the process I made some helper functions that might be beneficial to others.

### make_unit2()
The first is `make_unit2()`. (There is probably a better name for it, but this was the best I could come up with after a few minutes of thought).

This was to address some issues I had with `units::make_unit()`. The first is that `make_unit` does not parse strings correctly as expressions into denominator and numerator fields of the “symbolic_units” object.
```
format(units(make_unit("ug/l")))
##   numerator denominator 
##      "ug/l"          ""
format(units(make_unit2("ug/l")))
##   numerator denominator 
##        "ug"         "l"
```
This had downstream effects in that it a) interfered with unit simplification, and b) units were printed in parenthesis by default ("
```
format(make_unit("ug/l"))
## [1] "1 (ug/l)"
format(make_unit2("ug/l"))
## [1] "1 ug/l"
```
Finally, another issue was that make_unit would create units that were not valid or did not return true for `udunits2::ud.is.parseable()`. I think that flexibility is important to have, but I needed a version that would throw an error instead of create an invalid or unrecognized unit.
```
make_unit("foo")
## 1 foo
try(make_unit2("foo"))
```
`make_unit2()` is somewhat fancy in that it works with both strings or expressions. Here are some extended examples I included in the documentation:
```
# different ways to specify units
 # all 3 should be identical
 make_unit2(ug/l)
## 1 ug/l
 make_unit2("ug/l")
## 1 ug/l
 string <- "ug/l"
 make_unit2(string)
## 1 ug/l
 # valid unit names not found in units::ud_units also parse
 make_unit2(ug/gallon)
## 1 ug/gallon
 make_unit2("ug/gallon")
## 1 ug/gallon
 string <- "ug/gallon"
 make_unit2(string)
## 1 ug/gallon
 # the normal evaluation of the supplied argument is attempted first before
 # inspecting supplied expression. The expression is only inspected if it does
 # not resolve to a character vector"
 ug <- "kilogram"
 make_unit2(ug)
## 1 kilogram
 # note that even if one of the symbols is bound, NSE is done on the whole
 # expression or not at all
 make_unit2(ug/l)
## 1 ug/l
 # to avoid expression parsing, use argument .SEonly (e.g., defensive programmig
 # inside a function)
 # make_unit2(ug/l, .SEonly = TRUE) # ERROR
 make_unit2("ug/l", .SEonly = FALSE) # the default
## 1 ug/l
 make_unit2(ug, .SEonly = TRUE)
## 1 kilogram
 # some examples for how to convert units
 # first assign units to a numeric, this makes a vector with units
 x <- 1:3
 (units(x) <- make_unit2(ug/l))
## 1 ug/l
 # then, assigning units to a vector with units performs conversion
 set_units(x, make_unit2("mg/l"))
## Units: mg/l
## [1] 0.001 0.002 0.003
 set_units(x, make_unit2("g/l"))
## Units: g/l
## [1] 1e-06 2e-06 3e-06
 set_units(x, make_unit2("ug/tbsp"))
## Units: ug/tbsp
## [1] 0.01478677 0.02957353 0.04436030
 set_units(x, make_unit2(kg/US_liquid_gallon))
## Units: kg/US_liquid_gallon
## [1] 3.785412e-09 7.570824e-09 1.135624e-08
 # `set_units(x, u)` is a pipe friendly equivelant version of `units(x) <- u`
 (units(x) <-  make_unit2("mg/l") )
## 1 mg/l
 units(x) <- make_unit2(ug/l)

 # reserved words like in and special characters like % and ' must be
 # backticked if passed as bare expression, however they work just fine if
 # passed as a character string.
 make_unit2(`in`)
## 1 in
 make_unit2("in")
## 1 in
 make_unit2("%/gallon")
## 1 %/gallon
 make_unit2("%/'")
## 34.37747 1
 make_unit2("'/%")
## 0.02908882 1
 make_unit2(`%`/gallon)
## 1 %/gallon
 make_unit2(`%`*T)
## 1 %*T
 make_unit2(T/F)
## 1 T/F
 # make_unit2(T/FALSE) # ERROR

 # attempting to convert between incompatable units throws an error
 # units(x) <- make_unit2(ft) # ERROR
 # not recognized units throw an error
 # make_unit2(foo/bar) # ERROR
```

### .udunits_symbols_info()
Finally, since there are many more units than there are symbols in `ud_units`, and since `ud_units` does not come with a key, and since `make_unit2` accepts not only symbols but the full unit names, I wanted to easily pull up a reference for what are the accepted units. hence this function. Here, i parse the udunits2.xml file into a dataframe

```
.udunits_symbols_info()
## udunits system database read from C:/Users/kalinowskit/Documents/R/win-library/3.4/udunits2/share/udunits/udunits2.xml
## # A tibble: 275 x 11
##    source_xml_table_name symbol symbol_aliases name_singular
##                    <chr>  <chr>          <chr>         <chr>
##  1                  base      m                        meter
##  2                  base     kg                     kilogram
##  3                  base      s                       second
##  4                  base      A                       ampere
##  5                  base      K                       kelvin
##  6                  base    mol                         mole
##  7                  base     cd                      candela
##  8               derived    rad                       radian
##  9               derived     sr                    steradian
## 10               derived     Hz                        hertz
## 11               derived      g                         gram
## 12               derived      N                       newton
## 13               derived     Pa                       pascal
## 14               derived      J                        joule
## 15               derived      W                         watt
## # ... with 260 more rows, and 7 more variables:
## #   name_singular_aliases <chr>, name_plural <chr>,
## #   name_plural_aliases <chr>, def <chr>, definition <chr>, comment <chr>,
## #   dimensionless <lgl>
```
```
.udunits_prefix_info()
## udunits system database read from C:/Users/kalinowskit/Documents/R/win-library/3.4/udunits2/share/udunits/udunits2.xml
## # A tibble: 20 x 4
##    symbol symbol_aliases  name value
##     <chr>          <chr> <chr> <dbl>
##  1      Y                yotta 1e+24
##  2      Z                zetta 1e+21
##  3      E                  exa 1e+18
##  4      P                 peta 1e+15
##  5      T                 tera 1e+12
##  6      G                 giga 1e+09
##  7      M                 mega 1e+06
##  8      k                 kilo 1e+03
##  9      h                hecto 1e+02
## 10     da                 deka 1e+01
## 11      d                 deci 1e-01
## 12      c                centi 1e-02
## 13      m                milli 1e-03
## 14      µ           µ, u micro 1e-06
## 15      n                 nano 1e-09
## 16      p                 pico 1e-12
## 17      f                femto 1e-15
## 18      a                 atto 1e-18
## 19      z                zepto 1e-21
## 20      y                yocto 1e-24
```

If there is interest, I could submit a pull request with these 3 new functions.

**Comment by edzer** [comment]
Thanks for expressing interest! I think it is useful to have access to udunits symbols and prefixes, programatically. `units` already has functions to (re)create the `ud_units` object from the xml files, see [this](https://github.com/edzer/units/blob/master/R/ud_units.R) file; does your code integrate or align with that?

Parsing units in `make_unit` is desirable, but also the topic of #45 and #50; please give a pointer to your code so I can have a look at whether to import this from you, or from @ezwelty.

**Comment by t-kalinowski** [comment]
Hello, 

I did not see #45 before. At first gland that seems like it may have been helpful!

I posted the code in a gist here:
https://gist.github.com/t-kalinowski/05900156476a0c792623daa39175543b

The functionality that parses the xml database builds ontop of the code file you link too (it actually starts with a direct copy of it)

The general approach in make_units 2 is to recursively scan the expression and then wrap all bare symbols with a `units::make_unit` call, after checking that the expression is parsable with `udunits2::ud.is.parseable`

**Comment by t-kalinowski** [comment]
Oh, one more comment, currently the function has a dependency on rlang for the `quo` and `enquo` functions.... I assume that that additional dependency is undesirable here, and i think it would be fairly straightforward to remove...

**Comment by ezwelty** [comment]
@edzer For your reference, for purposes of comparison, here is a pointer to my code for parsing strings to units. Both our examples make for a good testing suite!

https://github.com/ezwelty/units2/blob/master/R/unit_strings.R#L42

@t-kalinowski I really like the idea of having an easy reference to all unit names, not just the canonical symbols. So thanks!

**Comment by t-kalinowski** [comment]
Thanks @ezwelty !

Thinking about this some more, I'm wonder if a better approach to recursively scanning the expression  or parsing via a complex regex is to instead do something like
```


nms <- all.names(expr)
nms <- setdiff(nms, c("*", "/", "^", "-"))
tmp_env <- lapply(nms, function(nm) {
  stopifnot(udunits2::ud.is.parseable(nm))
  make_unit(un)
})

eval(expr, tmp_env, baseenv())
```
(not tested)

**Comment by t-kalinowski** [comment]
actually,  this is more complicated and the naive approach above won't work. something like `quote(ft/m^2)` resolves to `0.3048 1/m`, when it should resolve to `1 ft/m^2` with slots:
```
$numerator
[1] "ft"

$denominator
[1] "m" "m"
```

**Comment by t-kalinowski** [comment]
this is even simpler
```
make_unit2 <- function(x) {
  expr <- substitute(x)   

  nms <- all.names(expr)
  nms <- nms[sapply(nms, udunits2::ud.is.parseable)]
  tmp_env <- lapply(setNames(nm = nms), 
    function(nm) units::make_unit(nm))
  
  eval(expr, tmp_env, baseenv())
}
```

**Comment by t-kalinowski** [comment]
Hi @edzer,
Thank you for incorporating some of #60 .
I haven't run the code yet, but I took a quick look and just reading the code I have 3 requests / questions:

1)  Would you mind adding an escape hatch to avoid NSE of the supplied expression here? Something like .SEonly as used here:
  if (!.SEonly &&  (!is.character(o) || inherits(o, "try-error")))
The units defined in the udunits xml are not always known, and therefor depending on ud.is.parsable is a little dangerous.

2)  If passing a string, can we add some automatic backticking of some common units that are invalid R code. In particular, i'm thinking of "in" (as in, inches).

3)  I see that warnings are now thrown if a unit name like "degree_C" is passed to make_units instead of a symbol... is that necessary? "degree_C" isn't really ambiguous, it resolves to something very specific in the udunits xml DB. These warnings will make lots of code noisy, and require ample use of suppressWarnings(). Can they be removed?

Happy to submit a PR if you'd prefer.

**Comment by edzer** [comment]
3: is not the case: degree_C is accepted, but as opposed to set_units not replaced by its symbol; 2: I don't know, and I'm not sure if it is worth the effort (and code mess) 1: maybe yes.

Frankly, I'm quite unhappy with the way things are now -- make_unit and set_units are nearly identical, yet have their differences. make_unit now suddenly needs an argument to specify user-defined units. Calls like make_unit(paste("m", "/", "s")) no longer work. I'm thinking about going back (revert this commit) and have set_units accept expressions, have make_unit only accept non-udunit units (user-defined), and parse_unit parse only the `km s-1` form. Three different functions for three different purposes.

**Comment by t-kalinowski** [comment]
I agree the current state is the three unit creation functions is a little confusing.... 
What if,

*  `make_unit(unit_as_string, user_defined = FALSE, engineering_notation = FALSE)` accepts only scalar character, with the current `user_defined` argument as an escape hatch to prevent parsing as an expression, and `engineering_notation` (or a better shorter name) to use the current `parse_unit("km s-1")` code path.

* `make_unit0()`, export, to mimic the current make_unit functionality, as a simple bare bones wrapper around `.symbolic_units`, or perhaps just export  `.symbolic_unit` (and remove the "s" to make clear that it is for a singular, symbolic unit)

`set_units()`  a (relatively) simple wrapper that takes only expressions, converts them to character, and then calls make_unit on them.

`parse_unit` deprecated, in favor of calling `make_unit(..., engineering_notation = TRUE)`
```

**Comment by t-kalinowski** [comment]
actually, rereading the above, I think it might be clearer if make_unit and parse_unit were consolidated onto parse_unit, and make_unit was deprecated

**Comment by edzer** [comment]
Would you also agree that this `parse_unit` should only return a `symbolic_unit`, to be used to create `units` objects by `set_units` or `units<-`?

**Comment by t-kalinowski** [comment]
yes.

**Comment by t-kalinowski** [comment]
`symbolic_unit()` should possibly have a warning option, default TRUE, to check and warn if the unit passes `ud.is.parsable`

**Comment by t-kalinowski** [comment]
I'm still not happy with this outline, it needs some more thought.

another potential approach: an exported function for power users , `.eval_units(expr)` which is essentially the `make_unit2` defined above, which take only expressions.  `parse_units` and `set_units` are only wrappers around `.eval_units(expr)`

**Comment by t-kalinowski** [comment]
What do you think of this:
```
# quoted expressions only, internal use.
.eval_units <- function(expr) {
  stopifnot(is.language(expr))
  
  nms <- all.names(expr)
  nms <- nms[sapply(nms, udunits2::ud.is.parseable)]
  names(nms) <- nms
  tmp_env <- lapply(nms, symbolic_unit, check_is_parsable = FALSE)
  
  eval(expr, tmp_env, baseenv())
}

# current make_unit, in essence.
symbolic_unit <- function(un, check_is_parsable = !user_defined, user_defined = FALSE) {
  stopifnot(is.character(un), length(un) == 1)
  if(check_is_parsable && !udunits2::ud.is.parseable(un)) {
    msg <- paste(sQuote(un), "is not a unit recognized by udunits")
    fun <- if(isTRUE(user_defined)) warning else stop
    fun(msg)
  }
  as_units.default(1, .symbolic_units(name))
}

# pipe friendly unit setter, accepts either a typed expression or a unit object
set_unit <- function(n, un) {
  expr <- substitute(un)
  try(force(un), silent = TRUE)
  if(!inherits(un, "symbolic_units"))
    un <- .eval_units(expr)
  
  units(n) <- un
  n
}

# parses strings as units, by default throws error if unit not recognized by udunits, with user_defined argument as option to return regardless. 
parse_units <- function(un, fractions_as_exp = FALSE, user_defined = FALSE) {
  stopifnot(is.character(un), length(un) == 1)
  if(fractions_as_exp)
    return(.parse_fractions_as_exp(un)) # current parse_unit()
  
  o <- try(expr <- parse(text = un), silent = TRUE)
  if(inherits(o, "try-error"))
    return(symbolic_unit(un, user_defined = user_defined, check_is_parsable = TRUE))
  
  .eval_units(expr)
}

# accepts only a bare (typed) expression
make_units(x) {
  .eval_units(substitute(x))
}
```

**Comment by t-kalinowski** [comment]
Can I submit a PR with these changes? I think discussion might be better there, where we can talk about specific versions of the PR.

I'll likely next have a chance to work on this and submit a PR late next week.

**Comment by edzer** [comment]
Sure, go ahead.
