### ISSUE TITLE
handle non-units in %*%

### ISSUE THREAD

**Issue by edzer** [r-quantities/units#62]
Right now, we have (building upon the example of the R Journal vignette)
```r
as_units(year_duration) %*% rep(1, length(year_duration))
```
through an error, where
```r
> as_units(year_duration) %*% rep(set_units(1), length(year_duration)) / length(year_duration)
Units: d
         [,1]
[1,] 365.2545
```
doesn't. This needs to be handled more gracefully.

**Comment by Enchufa2** [comment]
#127 finally dropped support for this operator.
