### ISSUE TITLE
Conflict with spatstat print.units()

### ISSUE THREAD

**Issue by andybega** [r-quantities/units#66]
When "spatstat" is attached, printing objects of class "units" fails (moved over from r-spatial/sf#523):

```r
library("units")

# works
set_units(1000, "m")
print(set_units(1000, "m"))

library("spatstat")

# error
set_units(1000, "m")
print(set_units(1000, "m"))

# but this works
units:::print.units(set_units(1000, "m"))
```

The error is:

```
Error: $ operator is invalid for atomic vectors
```

Because `spatstat`'s `print.units()` overrides the correct method. Changing the order in which packages are loaded does not help. `spatstat`'s `print.units()` is not exported as a S3 method.

Same issue at spatstat/spatstat#63.

**Comment by edzer** [comment]
Should be solved now that spatstat has moved to use `unitname` rather than `units` as their class.
