### ISSUE TITLE
Document how to remove units

### ISSUE THREAD

**Issue by barryrowlingson** [r-quantities/units#68]
I just spent way too long trying to remove units from a vector (because tmap failed if passed a vector with units), eventually SO told me to use `as.vector`. Could this be documented, perhaps on the units::units page?

**Comment by t-kalinowski** [comment]
`as.numeric` should work too.

**Comment by t-kalinowski** [comment]
I wonder if adding `units(x) <- NULL` as a way to remove units makes sense.

**Comment by edzer** [comment]
Yes, but
```r
> library(units)
> m = set_units(matrix(1:4, 2), km/s)
> m
Units: km/s
     [,1] [,2]
[1,]    1    3
[2,]    2    4
> as.vector(m)
[1] 1 2 3 4
> as.numeric(m)
[1] 1 2 3 4
```
so we may want to set methods that keep the `dim` attribute. `units(x) <- NULL` sounds good.

**Comment by t-kalinowski** [comment]
I just encountered this need while using `st_distance`. 
This seems to work fine:
```
drop_units <- function(x) {
  class(x) <- setdiff(class(x), "units")
  attr(x, "units") <- NULL
  x
}
```
