### ISSUE TITLE
conversion with user_defined units should work

### ISSUE THREAD

**Issue by t-kalinowski** [r-quantities/units#71]
```
cells <- symbolic_unit("cells", check_is_parsable = FALSE)
ml <- make_unit(ml)
l <- make_unit(l)
x <- 500

units(x) <- cells/ml
units(x) <- cells/l
# Error: cannot convert cells/ml into cells/L
```

**Comment by edzer** [comment]
This can be solved in `Rudunits2`:
```r
library(units)

# Attaching package: ‘units’

# The following object is masked from ‘package:base’:

#     %*%

library(udunits2)
# udunits system database read

ud.add.dimensionless("cell")

a = set_units(1, cell/l)
b = set_units(1, cell/ml)
a + b
# 1001 cell/L
```

**Comment by Enchufa2** [comment]
I think the user wouldn't have to know about `udunits2`. I would expect to `install_symbolic_unit` and/or `install_conversion_factor` and to obtain the same as with `ud.add.dimensionless`.

**Comment by edzer** [comment]
I agree, but it requires extensions of package `udunits2` before we can do this in `units`.

**Comment by t-kalinowski** [comment]
This feature might be incorporated upstream:
https://github.com/pacificclimate/Rudunits2/pull/9

**Comment by edzer** [comment]
... which has been open for 11 months now. @jameshiebert has pushing Rudunits2 any further still priority for you, or would you be happy if someone else took over?

**Comment by Enchufa2** [comment]
Oh, I see. I didn't realise before that the API exposed by udunits2 is very limited.

**Comment by holstius** [comment]
Thanks for the suggested workaround @edzer. I must be misunderstanding, as I can't find `udunits2:::ud.add.dimensionless()`, at least not in the current CRAN version (0.13). 

FWIW, my use cases are countable units like `person` or `vehicle` (for, e.g., `person*day` or `vehicle*mile`).

**Comment by edzer** [comment]
This was added to this fork: https://github.com/r-quantities/Rudunits2 and after that integrated (but renamed) in the `udunits` branch of the `units` source. We're now pretty close to releasing that to CRAN.

**Comment by Enchufa2** [comment]
```r
library(units)
#> udunits system database from /usr/share/udunits

install_symbolic_unit("cells")
x <- 500
units(x) <- "cells/ml"
units(x) <- "cells/l"
x
#> 5e+05 [cells/L]
```
