### ISSUE TITLE
units API overhaul

### ISSUE THREAD

**Issue by edzer** [r-quantities/units#75]
See #70 

Still TODO:
```
help of ?set_units: ... ; mention NSE


# This should not occur:
> units(b) = "10 m"
> b
Units: ^10*m
[1] 1 2 3


# This should be an error:
> b = 1:3
> units(b) = "10*m"
Warning message:
In ‘10 * m’ the numeric multiplier ‘10’ was discarded. 
The returned unit object was coerced to a value of 1.
Use `install_conversion_constant()` to define a new unit that is a multiple of another unit. 


# This should not occur:
> set_units(1:3, as_units("m"))
Units: 1
[1] 1 2 3
```

**Comment by t-kalinowski** [comment]
This is a tough edge case. Here, the call `as_units("m")` is passed on to as_units.call. `all.vars` returns a zero length vector, since there are no names or symbols in there, just a function and a constant (string). 

The best way to guard against this is explicitly I think. if `mode == "symbols`, add an check like this
```
 if (mode == "symbols") {
  value_expr <- substitute(value)
  value <- try(force, silent = TRUE)
  if (length(all.vars(value_expr) == 0L) && 
      (is.character(value) ||  inherits(value, "units") || inherits(value, "symbolic_units)
   stop("set_units requires a bare expression. set mode = "standard" to pass a bare string or units object")
  value <- value_expr  
}

```

or, better yet, move the error into as_units.call (where `x` is the expression)

```
constants_supplied <- vapply(x, is.character, logical(1L))
if(any(constants_supplied))
  stop("please supply only R symbols, not bare strings")
```

**Comment by t-kalinowski** [comment]
if we add that check into `as_units.call`, we'd have to modify `as_units.expression` to unwrap the list before passing on to the call, like this: 
```
as_units.expression <- function(x, ...) as_units.call(x[[1]], ...)
```

**Comment by t-kalinowski** [comment]
I added some more commits to related to this to #64, and trimmed a few other branches in the meantime. I think you'll have to merge then into the r-quantities/units/overhaul branch though, as I don't think I can push to that branch (please correct me if I'm mistaken)

**Comment by t-kalinowski** [comment]
```
> # This should not occur:
> units(b) = "10 m"
> b
> Units: ^10*m
> [1] 1 2 3

**Comment by t-kalinowski** [comment]
I addressed most of the TODO's, except this one:
```
# This should not occur:
> units(b) = "10 m"
> b
Units: ^10*m
[1] 1 2 3
```
This is the old `parse_unit` code path. Is it something you want to modify?

**Comment by edzer** [comment]
@t-kalinowski really impressive work! I think I'm close to merging into master. 

There is one minor thing: in `set_units` we now ask for a global option `getOption("units.set_units_mode")`, whereas in the plotting are we use package-dedicated options: see `?units_options`. I propose to stick with the second, agreed?

Would mean setting it by
```r
units_options(set_units_mode = "symbols")
```
I find that cleaner.

**Comment by t-kalinowski** [comment]
Thanks @edzer! 

I agree a single unified approach for setting package options makes sense. 

My only suggestion would be to keep the "option getter" code as the default value in the function formals, so it can serve as a hint to users that this is an easily adjustable or over-rideable setting.

**Comment by t-kalinowski** [comment]
To be consistent, `getOption("units.auto_convert_names_to_symbols", TRUE)` should be updated too.

**Comment by edzer** [comment]
OK, will do.

**Comment by edzer** [comment]
Still todo: modernize the `units.Rmd` vignette, remove using `with(ud_units...)` usage.

**Comment by edzer** [comment]
Merged in master through https://github.com/r-quantities/units/commit/4f74467333b458a29f692d37a9956800b0bff146.

**Comment by t-kalinowski** [comment]
Thank you @edzer!

**Comment by edzer** [comment]
Still to do:
```
b = 1:10
units(b) = "10 m"
```

**Comment by t-kalinowski** [comment]
I think the best way to approach this is to replace `.parse_unit_with_implicit_exponents()` [used here](https://github.com/r-quantities/units/blob/master/R/make_units.R#L231) and [defined here](https://github.com/r-quantities/units/blob/master/R/misc.R#L50) with a function called `convert_implicit_to_explicit_exponents()`. This should simplify and centralize the code-path, making it easier to maintain in the future.

**Comment by Enchufa2** [comment]
If I'm not wrong, the only thing still to do here is already tracked by #90, so we can close this, right?
