### ISSUE TITLE
Can't remove units

### ISSUE THREAD

**Issue by owenRiddy** [r-quantities/units#79]
My data has somehow become exposed to the units library through the sf package. I was executing the following:

areas <- st_area(sf)
areas <- areas[areas > 1000]
Error in Ops.units(ar, 100) : 
  both operands of the expression should be "units" objects

So it looks like a really handy library but obviously isn't built for calculation. I tried to remove the units but it seems there is a bug removing the units for a vector.

units(areas) <- NA
Error: inherits(value, "units") || inherits(value, "symbolic_units") is not TRUE

Could setting the units to NA please be fixed up to remove the units from the vector? Thanks.

**Comment by edzer** [comment]
The best would of course be to specify units in the comparison, as
```r
areas <- areas[areas > units::set_units(1000, m^2)]
```
but you can also remove the class of `areas` e.g. with
```
areas = unclass(areas)
```
before comparing to number.

Upcoming (develeopment) units version will allow for
```r
units(values) = NULL
```

**Comment by Enchufa2** [comment]
@owenRiddy Using `as.numeric` is another option. Anyway, note that `NA` has a special meaning in R ("missing") that is not appropriate in this case.

**Comment by owenRiddy** [comment]
Thanks
