### ISSUE TITLE
Support different time calendars other than gregorian

### ISSUE THREAD

**Issue by adrfantini** [r-quantities/units#80]
Some users, especially those using NetCDF files, sometimes have to do with 360-day calendars, or other weird types of calendars. I can only find two mentions of calendars in this repo and both are in comments.

Is this implemented in `units`?

**Comment by edzer** [comment]
Does udunits2 support it?

On 29 December 2017 12:49:36 CET, Adriano Fantini <notifications@github.com> wrote:
>Some users, especially those using NetCDF files, sometimes have to do
>with 360-day calendars, or other weird types of calendars. I can only
>find two mentions of calendars in this repo and both are in comments.
>
>Is this implemented in `units`?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/r-quantities/units/issues/80

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by adrfantini** [comment]
I'm not sure. I do not think so:
https://www.unidata.ucar.edu/software/udunits/udunits-current/doc/udunits/udunits2lib.html#Time

It seems UDUNITS specifically recommends using a separate calendar library.

Some more info:
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch04s04.html
https://www.unidata.ucar.edu/software/udunits/udunits-current/udunits/udunits2-common.xml

**Comment by edzer** [comment]
R pkg `units` does not do anything in this respect. You may want to try to define your own unit, with a conversion constant to a known unit, in case such a solution exists.

**Comment by adrfantini** [comment]
Looks like the only current option for 360/365-day calendars in R is using the package `PCICt`. I wonder if something like this could be implemented inside `units`?

**Comment by Enchufa2** [comment]
Neither udunits2 or (by extension) `units` are calendar packages. A true calendar package should be used instead for this purpose.
