### ISSUE TITLE
Combinations of user-defined+udunits2 units cannot be converted

### ISSUE THREAD

**Issue by Enchufa2** [r-quantities/units#84]
Maybe related to #71 (cc @t-kalinowski). I'm trying the following:

```r
library(units)

install_conversion_constant("c", "m s-1", 299792458)
light <- set_units(1, "c")
set_units(light, "m/s")
#> Error: cannot convert c into m/s
```

The installed conversion appears to fix r-quantities/constants#2, but the new unit "c" is *almost* useless, as any conversion fails.

**Comment by Enchufa2** [comment]
Actually, this works:

```r
install_conversion_constant("c", "m/s", 299792458)
light <- set_units(1, "c")
set_units(light, "m/s")
#> 299792458 m/s
```

But there is a deeper problem here, which is that conversions are too *exclusive*, in the sense that a unit must be user-convertible *xor* udunits2-convertible, but combinations won't work. Taking the example in r-quantities/constants#2, I would expect the following to work:

```r
# remotes::install_github("r-quantities/constants")
install_conversion_constant("c", "m/s", 299792458) # or "m s-1"
set_units(constants::syms_with_units$G_hbar.c0, "m3 kg-1 s-2")
#> Error: cannot convert c^4/GeV^2 into m^3/kg/s^2
```

But it doesn't, because "c^4/GeV^2" is not user-convertible nor udunits2-convertible, but it is user+udunits2-convertible!

Is it possible to register user-defined symbols directly into udunits2 at C-level? Otherwise, I see no easy fix, because every `from` may have any combination of user-defined and udunits2 units, and the same for the `to` side.

**Comment by Enchufa2** [comment]
So this is definitely the same as #71. Sorry for the redundancy, @edzer.

Considering the difficulty of this issue, I'm going to close r-quantities/constants#2 and submit an update to CRAN to fix the ERRORs there.

**Comment by edzer** [comment]
udunits2 has [ut_scale](https://www.unidata.ucar.edu/software/udunits/udunits-2.0.4/udunits2lib.html#Operations); see also #71.

**Comment by edzer** [comment]
gives this:
```r
ibrary(units)
library(udunits2)
# udunits system database read

ud.add.dimensionless("cell")
ud.add.scale("cellx", "cell", 10)

a = set_units(1, cell)
b = set_units(1, cellx)
a + b
# 11 cell

ud.add.scale("xkm", "km", 10)

x = set_units(1, xkm/cell)
y = set_units(1000, m/cellx)
x + y
# 1.01 xkm/cell
y + x
# 101000 m/cellx
```

**Comment by t-kalinowski** [comment]
This is great progress! 

One issue I foresee is that it throws errors if trying to map more than one scale to a new unit. For example
``` r
library(udunits2)

ud.add.dimensionless("cell")
ud.add.scale("cellx", "cell", 10)

ud.add.dimensionless("CFU") # colony forming unit == 4 cells
ud.add.scale("cell", "CFU", 4)
#> "cell" already maps to existing but different unit
#> Error in ud.add.scale("cell", "CFU", 4): Error in function R_ut_add_dimensionless: Unit, prefix, or identifier already exists
```

**Comment by edzer** [comment]
Yes, but this for instance works:
```r
library(udunits2)
ud.add.dimensionless("cell")
ud.add.scale("CFU", "cell", 4)
```
and gets what you want: CFU is a scaled version of cell.

I am currently trying to get more familiar with the `udunits2` API, and see how we can use it for how we now do things in `units` with user-defined units, or whether this needs change; this is all in branch `udunits` (which no longer requires R pkg udunits2). 

A challenge is that `udunits` sees all dimensionless units as convertible:
```r
ud.convert(1.0, "rad", "CFU")
# [1] 0.25
```

**Comment by Enchufa2** [comment]
BTW, my example above was wrong. It should be:

```r
library(constants)
with(
  syms_with_units, 
  set_units(G_hbar.c0 * hbar * as_units("c"), "m3 kg-1 s-2")
)
#> 6.674074e-11 m^3/kg/s^2
```

and works like a charm with the `udunits` branch. :)
