### ISSUE TITLE
No simplification of user defined units under division

### ISSUE THREAD

**Issue by seandavidross** [r-quantities/units#85]
> library("units")
> install_symbolic_unit("samples")
>
> qty <- set_units(100, "samples")
> 
> rate <- set_units(250, "samples/s")
> 
> duration <- qty / rate
>
> duration
+ 0.4 s\*samples\*samples^-1

The result should be "0.4 s"

**Comment by Enchufa2** [comment]
Thanks, we know. This is the same problem as #71 and #84, and there's a technical obstacle that does not depend on this package, but in `udunits2`. We are working on a solution, but it will take some time.

**Comment by Enchufa2** [comment]
Fixed in the current `master` branch (submitted to CRAN as v0.6-0).
