### ISSUE TITLE
Ci to Bq represented as Hz

### ISSUE THREAD

**Issue by Enchufa2** [r-quantities/units#88]
We have

```r
set_units(set_units(1, Ci), Bq)
#> 3.7e+10 Hz
```

It's true that both Bq and Hz are _the same kind_ of unit (frequency of something), but I don't want Hz if I requested Bq... Is this a problem of units or UDUNITS?

**Comment by edzer** [comment]
I think of SI units; internally, convertability is based on comparison of the powers of the 7 base SI units. Both are `s-1`; you can't specify _what_ happens, per second, and compare that. See also David Flater's paper and his suggestion to develop stronger types for the unit `1` (the what).

**Comment by Enchufa2** [comment]
Ok, understood. Closing this then.
