### ISSUE TITLE
as_units("10 m") vs. as_units("10m")

### ISSUE THREAD

**Issue by edzer** [r-quantities/units#90]
is clearly wrong:
```r
> as_units("10 m")
1 ^10*m
> str(as_units("10 m"))
Class 'units'  atomic [1:1] 1
  ..- attr(*, "units")=List of 2
  .. ..$ numerator  : chr [1:11] "" "" "" "" ...
  .. ..$ denominator: chr(0) 
  .. ..- attr(*, "class")= chr "symbolic_units"
```

**Comment by edzer** [comment]
`10 m` is interpreted differently by R:units and C:udunits2: R things it is (nothing) to the power 10 times m, C thinks it is 10 times m. I think the way out of this is to forbid unit strings with numbers in them with spaces around them: `"m3"` means cubic metres, `"m 3"` means metres times 3 (see [udunits2 grammar](https://www.unidata.ucar.edu/software/udunits/udunits-2.0.4/udunits2lib.html#Grammar)).

Interestingly, 
```r
as_units("10m")
```
seems to do the "right thing" (i.e., C and R representation correspond), but I'm not sure we want it. Also,
```r
a = 1:10
units(a) = as_units(10)
```
parses but does not give `a` units of 10, so should be an error.

**Comment by edzer** [comment]
Interestingly, we now have
```r
> as_units("10 m")
10 [m]
> as_units("10m")
1 [10m]
```
which is maybe not entirely what we want, but doesn't look like a bug anymore.

**Comment by Enchufa2** [comment]
I don't think this is a bug anymore either, but this needs to be discussed in the docs.
