### ISSUE TITLE
Make units install on fedora without custom configuration.

### ISSUE THREAD

**Issue by t-kalinowski** [r-quantities/units#92]
Installing udunits2 on fedora (27) requires a custom configure arg in order to install correctly:
```
install.packages("udunits2", configure.args='--with-udunits2-include=/usr/include/udunits2')
```
It would be nice if this was fixed in the next version of units and units knew to look there.

**Comment by Enchufa2** [comment]
+1! I'm a Fedora user and I have this in my `.Rprofile`, but it would be better if the configure script could handle it automatically.
