### ISSUE TITLE
Define a benchmark

### ISSUE THREAD

**Issue by Enchufa2** [r-quantities/units#99]
Given that we are experimenting and that the performance may be an issue, one important thing to do is to establish a benchmark to test different implementations.

**Comment by Enchufa2** [comment]
I've added some more code:

- The `xptr` branch has a version that is a simple Rudunits2 translation, encapsulated in C++.
- The `xptr_cache` branch has a more advanced version with reference counting, to avoid leaks and double frees, and a map-based cache system to resolve units from strings.

In both versions, I'm completely avoiding the use of `ut_trim`. Instead, I use `trimws` at R level. That way, we can decide when `trimws` should be used (the input comes from the user) or it's safe not to use it (the input comes from the package's internals), which is more efficient.

Feel free to play around with them. Comments welcome.

**Comment by edzer** [comment]
My understanding of the `XPtr` was that it takes care of leaks and double frees, relieving programmers from worries such as reference counting.

**Comment by Enchufa2** [comment]
It does, and it does many more things. To my understanding, the `XPtr` is not meant to replace a shared smart pointer. It's primarily intended to wrap objects that need to live between the R and C/C++ worlds. To do that, it needs to implement smart pointers capabilities, but also _talks_ to R to register finalizers among other things, so that, as soon as R loses track of that external pointer, it's ready to be safely gc'ed. This means that you _may_use them as smart pointers, but there could be trouble with R's gc.

In this case, I want the system-of-units object to live at R level, and the gc to be responsible of freeing it, so I use an `XPtr` for that. All the other objects (units and converters) are internal, and I don't want the gc to mess around with them. So basically I've implemented just what I need in a very thin layer (the `Ptr` class in `units.h`) responsible for automatically free the pointers returned by the udunits API.

**Comment by Enchufa2** [comment]
I did some informal benchmarking yesterday, and the speed is quite the same. There's some gain from the cache if the same unit is required many times, but it's small.

I was thinking about taking out the `xptr_cache` branch and using it to create a new package, `RcppUdunits2` for instance, with a clean and complete `udunits2` API. Would you be willing to switch to that package to remove the compiled bits from `units`?
